### ISSUE TITLE
add webgl 3d globe to microsite

### ISSUE THREAD

**Issue by max-mapper** [nodeschool/international-day#10]
http://hughsk.io/earth-triangulated/
- [ ] show events as dots
- [ ] animate globe to move around between dots in a loop

**Comment by iancrowther** [comment]
oooo very nice...

**Comment by max-mapper** [comment]
@nodeschool/owners anyone wanna take a stab at this? it doesnt have to be WebGL, it can be a normal mapbox map or even an SVG canvas. anything really!

**Comment by timoxley** [comment]
ping @hughsk

**Comment by hughsk** [comment]
Would be very happy to do so – setting aside some time to tackle it tomorrow night, but if anybody else wants to give it a shot then by all means do :)

**Comment by tdd** [comment]
BTW NodeSource did that when they launched to pinpoint their employees. Perhaps ask Joe McCann or someone there if they could "donate" the code and help us with this?

**Comment by xarus01** [comment]
Hi, if it is made by three.js maybe I can help.

**Comment by hughsk** [comment]
@tdd I'm the author of said globe :) Just asked NodeSource about this, they've given me some time to take it on so I'll have something ready to use by tomorrow! Sorry for the delay before.

**Comment by max-mapper** [comment]
WOOT!!!

**Comment by tdd** [comment]
Heu Hugh, that's AWESOME! :-)

## 

Christophe Porteneuve
tdd@tddsworld.com

**Comment by hughsk** [comment]
:grin:

WIP: http://nodeschool.io/globe/

@ogd do we wanna factor this into an existing design or should I build up some stuff around it? :)

**Comment by vikene** [comment]
@hughsk globe looks great  :+1:

**Comment by iancrowther** [comment]
it does, meant to say that earlier..

**Comment by hughsk** [comment]
Thanks @vikene @iancrowther @tdd :)

Done! I'll run through and clean it up a little, but let me know if you need anything else from me: http://nodeschool.io/globe/

**Comment by hughsk** [comment]
Oh another thing: currently showing a wider selection of events than is actually available, as there aren't any on the spreadsheet yet! The filter can be changed [here](https://github.com/nodeschool/globe/blob/f9c57774d88f5e7bdb97fceb4a1ef444ae8e6d6e/demo.js#L25-L28), but will want some events listed first or it'll break :)

**Comment by timoxley** [comment]
@hughsk amazing :cupid:

**Comment by timoxley** [comment]
It's a little feint is it not?

![image](https://cloud.githubusercontent.com/assets/43438/6914760/9c13afc2-d7c0-11e4-89fc-61a6b1c8417b.png)

**Comment by grabbou** [comment]
I would suggest slightly darker yellow (?) for the earth as it's quite hard to go through tbh.

**Comment by hughsk** [comment]
@timoxley that's weird, here's the intended color:

![screenshot_2015-03-31_9 35 48 am](https://cloud.githubusercontent.com/assets/569817/6923888/5ae70cec-d789-11e4-8bba-08fcb0035983.png)

Is there a similar issue with the NodeSource globe by any chance?

**Comment by iancrowther** [comment]
This is really great.

**Comment by finnp** [comment]
@hughsk The NodeSource globe works, but the NodeSchool globe only shows the "back color". Would love to see the globe on the /international-day side soon. However I would love the color scheme to not be yellow like the nodeschool.io website.
