### ISSUE TITLE
Create list of 2015 participants from github usernames

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#100]
I would really like to create a 2015-attendees.json file so we can render them on the website

**Comment by iancrowther** [comment]
I believe we can use the rollcall-2105 label of the github api

**Comment by lackerman** [comment]
Hi Ian, are you referring to the labels_url in the event type payload of the API?

There are labels for issues, repos and in events.

**Comment by iancrowther** [comment]
we added the label rollcall-2015 to a number of issues so we could try to create a rollcall

**Comment by iancrowther** [comment]
I created a script to build a list of attendees who participated in the rollcall issues

https://github.com/iancrowther/rollcall

https://raw.githubusercontent.com/iancrowther/rollcall/master/rollcall-2015.example.json

**Comment by lackerman** [comment]
Nice

**Comment by iancrowther** [comment]
could you help with some website updates? I created some new issues.

Ive tried to make them small and quick to do
