### ISSUE TITLE
create 2016 website

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#101]

**Comment by ismnoiet** [comment]
Hi, allow me to ask you this, what kind of help you want ?
 I imagine that you are talking about Nodeschool website aren't you ?
:)

**Comment by iancrowther** [comment]
I have started to add smaller issues for website updates.

initially we just want to clean up, add a grid and make the website approachable for beginners to chip in.

**Comment by ismnoiet** [comment]
@iancrowther good job and  i'm with you on this.

**Comment by iancrowther** [comment]
Ah and I'm talking about the node school international day website

**Comment by iancrowther** [comment]
first draft of the 2016 website https://github.com/nodeschool/international-day/pull/109
