### ISSUE TITLE
Add 2016 enrolled logos to website

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#106]
we have an enrolment form, so we can csv -> json and simply render
- logo url is a required form field

**Comment by iancrowther** [comment]
I have manually added London, but this really should be automated from now on

**Comment by martinheidegger** [comment]
It should be better than automated: Convention over configuration I say:

```
https://nodeschool.io/<chapter>/chapter.json // {name: 'Chapter Name', location: {lat: ..., lon: ..., name: '' }, contributors: [{}], admins: [{}]}
https://nodeschool.io/<chapter>/events.json // [{start: new Date(), end: new Date(), name: 'Crazy NodeSchool event', location: {lat: ..., lon: ..., name: '', url: ''}, signup: ''}]
https://nodeschool.io/<chapter>/badge.png (385x443)
https://nodeschool.io/<chapter>/badge.svg
```

**Comment by iancrowther** [comment]
ooo i like that a lot.. 
- why 385x443?
- how do we use this practically?

I figured once you fill in the form, your enrolled? 
Do we want chapters to put in a PR to add logo's etc?
Do we manually keep the list updated?

**Comment by martinheidegger** [comment]
385x443 ← Size now used on the homepage

I am working on a cli tool to set this up. Keeping you posted (of course: all automatic)

**Comment by iancrowther** [comment]
Legend 😀

**Comment by TylerMoeller** [comment]
With NodeSchool International Day only 11 days away, should I create a pull request to get our chapter listed on https://github.com/nodeschool/international-day/blob/gh-pages/index.html?

This would be the pr if you want to add it:

``` html
<div class="col s12 m3">
  <a href="http://www.meetup.com/IslandJS-Nodeschool/events/230953012/" class="black-text" target="_blank">
    <div class="card center hoverable">
      <div class="card-content">
        <h5 class="card-title ">Bainbridge Island</h5>
        <img class="chapter-logo" src="http://nodeschool.io/images/nodeschool-bainbridge.svg" alt="Nodeschool Bainbridge Island Logo">
      </div>
      <div class="card-action center">
        <span>Visit Chapter</span>
      </div>
    </div>
  </a>
</div>
```

**Comment by gaboesquivel** [comment]
I agree with @TylerMoeller ...  @costaricajs can also help, just let us know what needs to be done.

**Comment by martinheidegger** [comment]
@gaboesquivel The initial proposal was dumped. We need a PR that adds the logos of the registration form (google docs) directly on the page: https://docs.google.com/spreadsheets/u/2/d/1XHEtzfLpixcQpogVzNdm-sVVqw4YHJ1IBllCk5H9oyc/export\?format\=csv\&id\=1XHEtzfLpixcQpogVzNdm-sVVqw4YHJ1IBllCk5H9oyc\&gid\=1860810608

**Comment by gaboesquivel** [comment]
@msolano00 is working on it. 
Please link your PR to this issue.  Thanks !

**Comment by msolano00** [comment]
Hey guys, I have a quick question, I cloned the original repo, but @TylerMoeller has now updated the index, so I am wondering if I should clone Tyler's repo (in order to keep record of the previous badges), work over it, merge it to mine and then boom make a pr.

**Comment by msolano00** [comment]
International-day chapter badges #125
