### ISSUE TITLE
Worldwide video broadcast

### ISSUE THREAD

**Issue by grabbou** [nodeschool/international-day#11]
What you guys think about creating Hangouts all-over-the-globe video conversation? Not sure if that can work, but getting live stream from each chapter and putting that onto a grid would be awesome. Just to show we are everywhere.

**Comment by grabbou** [comment]
Sounds like similar to @maxogden idea posted here #9. Closing then.

**Comment by Sequoia** [comment]
This sounds different because @maxogden is talking about recording for after & this is about chatting day of, yes? Personally I would love to have 1 or 2 computers doing telepresence to other events so people could walk up to them & chat.

**Comment by grabbou** [comment]
Well, this can work as well. Actually I've created yet another issue in main repo - https://github.com/nodeschool/organizers/issues/164 that sounds a bit different from what I've written above, but generally - I was always impressed by "big names" in JS community doing all those things and as I said - this might be an awesome experience for everybody (not only for attendees)

**Comment by iancrowther** [comment]
ok that is a cool concept, lets see if it can tie it into the film req's, and the handover req's, of course tbd ;-)
