### ISSUE TITLE
website nav breaks on mobile

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#113]

**Comment by lackerman** [comment]
The solution on this is very dependent on the behaviour you're looking for. Possible solutions:
1. Default for materialize is to collapse to the hamburger icon
2. Drop the text from options and only leave the icons
3. Show all available options and put the remaining (those that don't fit) into a dropdown

**Comment by iancrowther** [comment]
Which do you recommend?

**Comment by lackerman** [comment]
I quite like the icons only but it could detract from usability. 

Also, I assume the website is under the `gh-pages` branch. 

Is the site being generated by some other tool?

**Comment by iancrowther** [comment]
yeah gh-pages, usability is #1 so text links for certain?

it not being generated, its simple html/css to be easy to work with

**Comment by a0viedo** [comment]
@nisnardi @durancristhian maybe you could give a hand with this?

**Comment by lackerman** [comment]
Ok, we need to include the JS from [Materialize](http://materializecss.com/getting-started.html) to enable the default hamburger behaviour - instead of custom rolling it. 1 Question though, why are you including the CSS instead of pointing to the CDN?

**Comment by iancrowther** [comment]
just so I could explore to css with ease, happy to use cdn

**Comment by iancrowther** [comment]
Looks great
