### ISSUE TITLE
mobile styling for 2015 attendees needs some attention

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#114]

**Comment by a0viedo** [comment]
@nisnardi @durancristhian maybe you could give a hand with this?

**Comment by durancristhian** [comment]
Hi everyone, what we can do with this?

**Comment by iancrowther** [comment]
I'm not sure to be honest, have a look at the site on mobile. The 2015 rollcall is a bit linear. I'm not sure how to make it look nicer though

**Comment by durancristhian** [comment]
Hi @iancrowther,

I've been playing a little with the site and the Chrome DevTools. I'm not sure what we can do to make it look better. However, I've added some styles to adapt the list a little bit "better" the responsive breakpoints and also added a hover state to each <li>

![aa](https://cloud.githubusercontent.com/assets/4248944/12223385/da966828-b7b4-11e5-961c-eefac215e8a5.jpg)

I'm not sure if that is something useful for us and design is not one of my strengths (if there is one haha). What do you think about it?

**Comment by iancrowther** [comment]
i think that's a nice improvement :-) PR?

**Comment by durancristhian** [comment]
@iancrowther done :+1:

**Comment by iancrowther** [comment]
yay, ty
