### ISSUE TITLE
Invalid nodeschool london icon path 

### ISSUE THREAD

**Issue by ismnoiet** [nodeschool/international-day#116]
There is an error for the london sticker path in the [Internatinoal day](http://nodeschool.io/international-day/) web page. A solution may be to replace it with a reference to the sticker icon  : 

(a working path )[https://raw.githubusercontent.com/nodeschool/nodeschool.github.io/source/images/nodeschool-london-official.png]

By the way what you think about linking chapter icons to 
`https://raw.githubusercontent.com/nodeschool/nodeschool.github.io/source/images/` + `whatever chapter name`.
This way we avoid having duplicate chapter icons and stickers.

What you think about it guys ?

**Comment by iancrowther** [comment]
it works if everone uses gh-pages, but not everyone does.  and tbf, it should not be a contraint

how about a "convention" of `/resources/sticker.png`

**Comment by iancrowther** [comment]
What is the issue? can you screen shot? im struggling to re-create?

**Comment by ismnoiet** [comment]
I've changed the wrong image path (under gh-pages) with the correct one,.
and now it is working  :)
