### ISSUE TITLE
International Stickers

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#119]
It would be cool to have pre-ordered stickers from the chapter your will say hi too!

this needs some prep if it's to become more than a nice idea.

@martinheidegger will the new awesomeness help us here?

**Comment by rosskukulinski** [comment]
@iancrowther don't know if you're lining up corporate sponsors, but if not, I'd be happy to chip in some money for stickers

**Comment by iancrowther** [comment]
I've leant away from it so far, but it would be cool to send out some int sticker packs!

**Comment by martinheidegger** [comment]
Probably too late now. Closing Issue.
