### ISSUE TITLE
Schedule, Plan, what do we need to prepare?

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/international-day#12]
I have been asked following things, to which I knew no anser:
- What time does it start? (timezone?)
- What is the plan for us to do there?

**Comment by Sequoia** [comment]
My $.02:
1. Whenever is convenient for you
2. Observe the holiday however works best for you.

Personally I plan on holding an all-day event with a session in the morning & one in the afternoon, each session being comprised of a talk introducing nodeschool or the concept in the lesson followed by time for workshopping. Lunch 1/2 way thru if we can get sponsorship. I don't plan for a ton of "social" type time outside of lunch but I'm trying to figure out a way to include more mingling time without overpacking the schedule even more.  Attendees will mostly just be STARTING workshoppers during the event-- we'll use that time together to get started on a couple lessons & use the forums in the following weeks for lesson completion & help etc.

I'd _like_ to establish video-links with a couple other nodeschool events if possible.

**Comment by iancrowther** [comment]
So this indeed needs some prep and solid communication.  

1) I would suggest we start the day in Oceania and follow the sun.

2) We need to put a guide together, eg handover, rollcalls etc.

Shall we start with [PARTICIPATING.md](https://github.com/nodeschool/international-day/blob/2015/PARTICIPATING.md)

Once it has a few items worth discussing, we can schedule a hangout..

**Comment by bajtos** [comment]
Here is my provisional plan/schedule for Hradec Kralove (CZ):

| [BST](http://en.wikipedia.org/wiki/British_Summer_Time) | [CET](http://en.wikipedia.org/wiki/Central_European_Time) | Schedule |
| --- | --- | --- |
| 8.00 | 9.00 | Registration opens |
| 8.15-8.30 | 9.15-9.30 | a short talk introducing the workshops. |
| 8.30-10.30 | 9.30-11.30 | workshops |
| 10.30-12.00 | 11.30-13.00 | lunch break |
| 12.00-14.00 | 13.00-15.00 | workshops |
| 14.00-14.30 | 15.00-15.30 | afternoon break |
| 14.30-16.30 | 15.30-17.30 | workshops |
| 16.30-17.00 | 17.30-18.00 | a final talk, retrospective |
| 17.00 | 18.00 | move to a pub. |

**Comment by martinheidegger** [comment]
Looks good! I think the osaka one I imagine right now somehow like:

| [BST](http://en.wikipedia.org/wiki/British_Summer_Time) | [JST](http://en.wikipedia.org/wiki/Japan_Standard_Time) | Schedule |
| --- | --- | --- |
| 2.45 | 10.45 | Registration opens |
| 3.00-3.15 | 11.00-11.15 | A short introduction |
| 3.15-5.00 | 11.15-13.00 | workshops |
| 5.00-6.30 | 13.00-14.30 | lunch break |
| 6.30-8.15 | 14.30-16.15 | workshops |
| 8.15-8.45 | 16.15-16.45 | afternoon break |
| 8.45-10.30 | 16.45-18.30 | workshops |
| 10.30-11.00 | 18.30-19.00 | a final talk, retrospective, clean up |
| 11.00 | 19.00 | move to a pub. |

(@bajtos: I took the liberty to reformat the schedule and add GMT information)

**Comment by sericaia** [comment]
Our schedule to Lisbon (Portugal):

| BST | Schedule |
| --- | --- |
| 09:30 - 10:00 | Intro and setup |
| 10:00 - 12:30 | **Track 1**: Learn Javascript and Node.js; <br>**Track 2**: Pick a workshopper, make a group, hack something AMAZING! |
| 12:30 - 14:00 | Lunch break |
| 14:00 - 17:30 | Keep on learning or keep on hacking! |
| 17:30 - 18:00 | Everyone gets a chance to present something they've been doing during the day |
| 18:00 - 18:30 | enLIGHTNING Talks: we'll have some amazing speakers talking about Node real life projects |
| around 18:30 | We'll enjoy Lisbon evening by grabbing some beers & eating sardinhas or caracóis! |

**Comment by iancrowther** [comment]
Hi All,

Thanks for the above.  We just need an schedule overview.  I have created a csv which gives us this.  can you please review it and check your details are correct?  

https://github.com/nodeschool/international-day/blob/2015/international-nodeschool-schedule.csv

Thanks
