### ISSUE TITLE
2016 Stickers

### ISSUE THREAD

**Issue by Sequoia** [nodeschool/international-day#121]
This is by no means crucial, but if someone wants to create an event sticker for 2016 that would be totally groovy!
## Resources
- [Last years sticker thread](https://github.com/nodeschool/international-day/issues/7)
- [Last years stickers (ai, svg)](https://github.com/nodeschool/international-day/tree/2015/Stickers).

As mentioned, this is low priority, but if someone wants to do it it should be done ASAP-- it's getting on too late to order stickers w/o rush.

**Comment by Sequoia** [comment]
paging @dayrachiu, champion of stickers 2016! 👑

**Comment by robbiethegeek** [comment]
Please ping out if this happens so we can order for the DC crew!

**Comment by Sequoia** [comment]
Too little time for this. Here's a link to last years stickers, order rush today if you want 'em (in USA): https://www.stickermule.com/en/marketplace/5544-nodeschool-international-sticker
