### ISSUE TITLE
fix the timezones in the spreadsheet

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/international-day#123]
For some reason we forgot to specify the format of the timezone in the form. Now the timezones are all-over-the place. It would be awesome if someone could convert it to [Standard TZ's](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) _(Note: The TZ field like: `America/Costa_Rica`)_

Here is the sheet: https://docs.google.com/spreadsheets/d/1XHEtzfLpixcQpogVzNdm-sVVqw4YHJ1IBllCk5H9oyc/edit?usp=sharing

(Note: if you don't have edit permissions: Copy&Paste the fields here or ask for edit permissions on gitter)

**Comment by TylerMoeller** [comment]
Leave the spreadsheet sorted as is, by TimeStamp, and paste the following list over the contents of the Time Zone column (`I`):

```
Europe/London
America/Los_Angeles
America/New_York
America/Toronto
Europe/Lisbon
America/New_York
Europe/Zagreb
America/New_York
America/Mexico_City
America/New_York
America/Los_Angeles
Atlantic/Reykjavik
Asia/Kolkata
America/Tijuana
Asia/Kolkata
America/Los_Angeles
America/Los_Angeles
Europe/Rome
America/Costa_Rica
America/Bogota
Asia/Tokyo
Europe/Berlin
Europe/Madrid
Europe/Belgrade
America/Toronto
America/Argentina/Buenos_Aires
Asia/Dhaka
Asia/Kolkata
```

**Comment by TylerMoeller** [comment]
I have updated the Time Zones in the spreadsheet. Feel free to close this issue.

https://docs.google.com/spreadsheets/d/1XHEtzfLpixcQpogVzNdm-sVVqw4YHJ1IBllCk5H9oyc/edit?usp=sharing

**Comment by msolano00** [comment]
Verified the timezones, thanks a lot @TylerMoeller!
