### ISSUE TITLE
remove 2015 Attendees section from site

### ISSUE THREAD

**Issue by gaboesquivel** [nodeschool/international-day#124]
I don't see point of listing the names of last year's even.  specially since it is very incomplete.
Instead we should have more info about this years event.

**Comment by TylerMoeller** [comment]
Agree. Maybe we can replace with Fun Facts from 2015 to resolve this issue as well: https://github.com/nodeschool/international-day/issues/112

**Comment by gaboesquivel** [comment]
yeah, that's interesting.

also more stuff related to 2016,   embedded broadcasting channel, twitter feed, etc.

**Comment by msolano00** [comment]
Closing this issue as the section was removed, linking this to issue #112 in order to propose further ideas.
