### ISSUE TITLE
Hyphens don't work in the hashtag.

### ISSUE THREAD

**Issue by robbiethegeek** [nodeschool/international-day#127]
Let's switch the hashtag to #nodeschoolday

**Comment by yoshuawuyts** [comment]
confirmed - hypens don't work; `#nodeschoolday` seems reasonable

**Comment by gaboesquivel** [comment]
👍

**Comment by TylerMoeller** [comment]
There's still one remaining at the bottom of the readme. 

`Tweet using the #hashtag #nodeschool-day`  

Issue also discussed here: https://github.com/nodeschool/international-day/pull/115

**Comment by TylerMoeller** [comment]
Closing as Fixed. 
- https://github.com/nodeschool/international-day/pull/129/commits/e09017b27cb557366efb58f3de4c2afe209613c9
- https://github.com/nodeschool/international-day/commit/336e55ed0ea8babcd6bbf04da015c4c14b682890
