### ISSUE TITLE
Proposal: telepresence chain Around The World

### ISSUE THREAD

**Issue by Sequoia** [nodeschool/international-day#13]
So I would like to do some telepresence to other events to strengthen the "international"/celebratory atmosphere at our event. One Big Google Hangout has been proposed but I fear this would be sort of a cluster-fork and not that useful ultimately (an ad-hoc, high latency conversation among 10 parties who don't know eachother seems tough).  I'd prefer to have 1 or 2 or 3 direct links to _single_ events, so you could walk up to a screen at our event & see/hear/talk to someone at an event somewhere else, 1:1 (or in groups but 1 party :left_right_arrow: 1 party rather than 6 party FFA).
# Proposal
1. Create a list of people interested in this sort of telepresence at their event
2. Each event coordinates (ideally) with 1 event **west** of them, and 1 **east** of them
3. Now we (sort of) have a chain going around the world, link by link!
## Additional stuff
- The more links the merrier but this proposal says "prioritize getting 1 east & 1 west _first_"
- This will be tough across the atlantic-- basically if I had a East Coast to UK link it would go dark on our end around noon & wouldn't start on their end 'til maybe 3pm, but that's OK! :+1:
- Organization is light-weight: all that's needed is a list & description & people to point to it; event coordinators can add themselves to the list & reach out to other events directly & update the list when they've got someone east or west so it's easy to see who needs a partner still (i.e. no need for central coordination)
## :rainbow: :two_men_holding_hands: :two_women_holding_hands:

If we linked events in a direct chain, someone at an event in India could pass a message to someone in London thus:
1. Pune person tells person in Dubai to tell London "what's up!!"
2. Dubai passes message to Cairo
3. Cairo to Athens
4. Athens to Prague
5. Prague to Zurich
6. Zurich to Brussels
7. Brussels tells London "Pune says 'What's up!!!'"

:smile_cat: could be fun. would of course require more than 1:1 link coordination so there was an unbroken chain.

**Comment by iancrowther** [comment]
Love it.. We could update the site with the handover msg :-)

**Comment by grabbou** [comment]
Huh, there are already so many topics about video converstations that I start forgetting to answer in all of them. Can we set up a Hangouts call or something and work it out all together? Would love to connect from GMT+1 with somebody from more `fancy` timezone!

**Comment by Sequoia** [comment]
We're 9-4 gmt-5, so 3am-10am gmt+1 I think? Would love to set up a hangout
for around 9:00-9:30 our time (during coffee/registration) if you're
interested!

**Comment by grabbou** [comment]
Yeah should be a lunch time in Poland so sounds good to me :)

**Comment by Sequoia** [comment]
Great! Can you email me so we can coordinate details? Mine is
sequoia.mcdowell@gmail.com @grabbou

**Comment by iancrowther** [comment]
I think I duped

https://github.com/nodeschool/international-day/issues/48https://github.com/nodeschool/international-day/issues/48

Can you take ownership of this?

**Comment by iancrowther** [comment]
https://github.com/nodeschool/international-day/issues/5

**Comment by Sequoia** [comment]
I overreached with this idea. :) good idea but I can't handle it. Sorry for proposing something I can't bottom-line-- I know I broke the OSS code! :smile_cat:

**Comment by iancrowther** [comment]
Join us at http://appear.in/nodeschool
