### ISSUE TITLE
We have got a big screen-wall, what to do with it?

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/international-day#14]
OIT (Osaka institute of technology) will open their place for our international day in osaka :heart: . and they have a pretty big (massive?) 5x3 3dscreen display system setup there with a neat processor farm backing it up. 
I wonder if we could use them for something :smirk:  They are experimenting with using node.js to control the displays.

Also, they have two industrial conferencing cameras and if necessary 2 additional, slightly older, video walls o_O 

I further heard that they are in partnership with the Boston University (that has a similar/same setup). Wouldn't it be cool if Node.JS where to join from there (not sure that is possible)...

**Comment by iancrowther** [comment]
@martinheidegger sounds good, prb best for the chapter to own this.. Loving the fact that there are mini collaborations going on.. 

the only thing i would ask is that we capture some cool video for the mini-film..

**Comment by iancrowther** [comment]
@martinheidegger anything doing with this or shall we close?  This maybe a thing for the panel show :-)

**Comment by martinheidegger** [comment]
I will definitely do something with it. Not sure what yet :)
