### ISSUE TITLE
Organisers Checklist

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#145]
Please can chapter organisers:

<img width="453" alt="screen shot 2016-05-21 at 10 32 54" src="https://cloud.githubusercontent.com/assets/76060/15447584/64f586e2-1f3f-11e6-82b7-0d6985ecaf32.png">
- Upload photos and video of your event
- Fill in the feedback form

Why....?

To be part of this years [video](https://www.youtube.com/watch?v=V7YkuOrfhe0)

**Comment by iancrowther** [comment]
cc'd @awaterma,
@patrickheneise,
@stojanovic,
@abyv,
@somsharan,
@finnp,
@a0viedo,
@gaboesquivel,
@zhdzmn,
@dayrachiu,
@koustuvsinha,
@marcopiraccini,
@usmantahirr,
@sericaia,
@iancrowther,
@gmauricio,
@jeduan,
@gautamarora,
@fauntleroy,
@martinheidegger,
@cronopio,
@pin3da,
@jonalvarezz,
@brianpmarks,
@baering,
@jedireza,
@NorthDecoder,
@kohei-takata,
@darcyclarke,
@lrlna,
@robbiethegeek,
@Sequoia,
@dinodsaurus

**Comment by usmantahirr** [comment]
Event going on :D

**Comment by iancrowther** [comment]
@usmantahirr come say hello.. 
- Chat: http://gitter.im/nodeschool/international-day
- Video Wall: http://appear.in/nodeschool

**Comment by usmantahirr** [comment]
Video going live here
https://www.facebook.com/CareAxiom/videos/1109200842451552/

**Comment by iancrowther** [comment]
@usmantahirr can you upload a copy to google also for video editing.
