### ISSUE TITLE
idea: publish a module to npm for your chapter (like npm install berlin -g)

### ISSUE THREAD

**Issue by max-mapper** [nodeschool/international-day#15]
Had this crazy idea just now --

For international day, a group activity can be putting together a CLI module for your chapter. For example I could `npm install berlin -g` to get the `berlin` CLI tool. When I run `berlin` I should get instructions in my CLI in German that help me join the berlin chapter, install the first workshop and get any other basic info I need.

These CLI modules could be a good 'first install' experience for people new to the command line. Once they get `berlin` installed they can join the Berlin discussion board https://github.com/nodeschool/berlin/issues and sign up for the next event, or install one of the nodeschool workshops. When Berlin does a workshop they can have people start by installing the berlin CLI tool from NPM.

This could be a cool way for groups that come to international day to team up and publish a real thing during the day. They can include things in their module like https://www.npmjs.com/package/picture-tube or ascii animations.

This is a rough idea, feedback welcome!

**Comment by Sequoia** [comment]
will have [nodeschool course on building shell tools](https://github.com/Sequoia/clijs/) soon!! It's >50% done I think... :palm_tree:

**Comment by iancrowther** [comment]
nice..

**Comment by a0viedo** [comment]
Cool idea! I thought on making some T-Shirts with `npm i mentor -g` on the front also. The [mentor](https://github.com/a0viedo/mentor) CLI tool would give you the name of a random NodeSchool mentor around the world. I added the NodeSchool Buenos Aires crew, but it would be great if every one of you could send a PR.

**Comment by iancrowther** [comment]
@maxogden - Can you add this to the [participating guide](https://github.com/nodeschool/international-day/blob/2015/PARTICIPATING.md)

**Comment by iancrowther** [comment]
@a0viedo can you update participating and close this issue. ty
