### ISSUE TITLE
Distributed Computing Cluster

### ISSUE THREAD

**Issue by sunnyrjuneja** [nodeschool/international-day#16]
It would be awesome if we had a nodeschool event which everyone wrote a node in a distributed system.  Ideally, something that would become "more powerful" as more people join it. I was thinking something along the lines of a parallel computing, torrent, or something block chain like. Security/noob friendly are both big considerations. 

Maybe a torrent of the latest node/iojs release? Or the nodeschool image?
Or a map of everyone connected at the same time that doesn't use a central server?

Here's some prior art/ideas:
https://stripe.com/blog/ctf3-launch
http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-824-distributed-computer-systems-engineering-spring-2006/projects/

**Comment by No9** [comment]
Hey @whatasunnyday
Put together a workshopper for creating torrent networks for international day https://github.com/No9/torrential 
It's meant to be simple but we could add a couple of extra steps so people join a global network?

**Comment by sunnyrjuneja** [comment]
@No9 That was really interesting. I learned a bit about torrents. How about we use something like [DHT](http://www.bittorrent.org/beps/bep_0005.html) to transmit geolocation and build a visualization tool using something like [DataMaps](http://datamaps.github.io/)? If you're interested, maybe we can append it to your current NodeSchool.

**Comment by No9** [comment]
Thanks for the feedback

:+1: on DHT and visualisation  
Are you thinking of https://github.com/feross/bittorrent-dht ?
Maybe wrap it as another command line utility as a diving into a coding a DHT might be a bit of a leap?

Then have the DataMap linked to the bootstrap nodes of the DHT so we can see folks joining the network? 

Anyhow more than interested in having it in the current node-school so any feedback or code greatly received.

**Comment by grabbou** [comment]
Maybe kind of central socket.io server that each chapter can connect with? (then think of what to do with connections)

**Comment by iancrowther** [comment]
@whatasunnyday can you move this into a broader nodeschool discussion.  Its prob not getting the attention it deserves in this repo

**Comment by sunnyrjuneja** [comment]
@iancrowther sure where to? mailing list? github repo? i don't know much about where NS discussions happen.

**Comment by grabbou** [comment]
Well, `organizers` repo?
