### ISSUE TITLE
create event map (need help compiling data)

### ISSUE THREAD

**Issue by max-mapper** [nodeschool/international-day#19]
Can someone take the [Enrollment thread](https://github.com/nodeschool/international-day/issues/8) and turn it into a CSV like this:

```
name,lat,lon,chapter-url
"NodeSchool San Francisco","37.77493","-122.41942","http://github.com/nodeschool/sanfrancisco"
```

lat/lon can be approximate, e.g. the city. URL can be the nodeschool org or an even url if one exists

Then I can plug that data into http://nodeschool.io/globe and embed the globe on the nodeschool homepage for a while, so people can find local chapters easily

You can put the CSV here or check it into this repo, then we can update as new chapters enroll later

**Comment by grabbou** [comment]
Will have few hours free this weekend so can do that if still needed.

**Comment by afronski** [comment]
I've hacked small and _really ugly_ script - [here it is](https://github.com/afronski/playground-nodejs/tree/master/tools/comments-gh-scraper). :wink:

@maxogden CSV results are available [here](https://github.com/afronski/playground-nodejs/blob/master/tools/comments-gh-scraper/output.csv). If something is incorrect (e.g. geo coordinates), just ping me back - I'll fix it. Unfortunately, some chapters does not have even a github organization at all (e.g. _Brussels_).

**Comment by grabbou** [comment]
``` js
if (name === "wrocław") {
        return "https://github.com/nodeschool/wroclaw";
    }
```

Yay! Thanks :D

**Comment by afronski** [comment]
FTR: Thanks to @martinheidegger, we've much more awesome script and [nicer data](https://github.com/afronski/playground-nodejs/blob/master/tools/comments-gh-scraper/output.csv). :smile:

**Comment by afronski** [comment]
Script moved to this repo with #40 - @martinheidegger @maxogden should we close this issue? ;)

**Comment by max-mapper** [comment]
awesome! i'll make the globe now
