### ISSUE TITLE
agree a date

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#2]

**Comment by iancrowther** [comment]
May 9th

**Comment by mcollina** [comment]
Is it decided, or just proposed? I'll see if we can participate with an
Italy event :D
Il giorno mer 21 gen 2015 alle 09:20 Ian Crowther notifications@github.com
ha scritto:

**Comment by elf-pavlik** [comment]
So far on May 9th I plan to participate in [IndieWebCamp Germany 2015](http://lanyrd.com/cchbbw) but I don't see it as collision :wink:

**Comment by iancrowther** [comment]
@elf-pavlik can you integrate it into the day perhaps?

**Comment by iancrowther** [comment]
@mcollina - yes consider it decided (unless we have a huge roadblock)

**Comment by elf-pavlik** [comment]
@iancrowther yeah! sounds like good chance for cross-polination :bee:

**Comment by iancrowther** [comment]
gotta love them bees :-)

**Comment by bajtos** [comment]
Friday May 8th is a public holiday in Czech Republic, most people will be away for the long weekend. May 16th would suit our country more.

**Comment by timoxley** [comment]
I'd like to plug somewhere between May 22 – May 25. This is when CampJS V is happening and, as always, we're going to be launching **multiple new nodeschool workshops** and running a nodeschool for the duration of the event.

Picking this date could also have some sentimental significance as learnyounode was created for, and run for the first time, at CampJS II. I like to think of CampJS II as the birthplace of nodeschool (and stream-adventure was nodeschool's conception?).

**Comment by iancrowther** [comment]
@timoxley good shout that..
@bajtos thanks for letting me know, I had not considered public holidays!

I have created an enrolment form which is intended to gauge the appetite for this event and try to understand any date feedback.  Once we have a dataset, we can make a sensible call on the date.

http://goo.gl/forms/Nwd3swnpqN

**Comment by iancrowther** [comment]
results are here:

https://docs.google.com/spreadsheets/d/1KdAYUZRFfi0KliU9DlV1Xyy1EmvlyGUj4eFeRh4qOlU/edit?usp=sharing

**Comment by michaelgrilo** [comment]
Saturday, May 16 has the votes. However, @timoxley gave some great context as to why the following week could have more meaning. Let's see if we can work towards a consensus. 

@timoxley, if the International NodeSchool Day happens on May 16, are you likely to bypass that date and organize around CampJS V anyhow?

@bajtos, @julianduque, and @martinheidegger: do you think May 23 could work in your cities? 
_Sorry for the assumptions on who the points of contact might be for these places._

**Comment by martinheidegger** [comment]
@michaelgrilo don't see a problem with May 23 atm.

**Comment by jasonrhodes** [comment]
I'd be interested in possibly coordinating a Baltimore event. The 16th
probably works better for anyone involved in JSConf on May 27-29 but the
23rd would be fine even so, most likely.

**Comment by julianduque** [comment]
@michaelgrilo May 23 works for Medellin

**Comment by michaelgrilo** [comment]
Now that we have possible dates narrowed down a bit, let's get some input from more NodeSchools around the globe. 

@abyv, @adambutler, @adroittech, @Andersos, @aredo, @asbjornenge, @avin45h, @AVVS, @awaterma, @az7arul, @bevacqua, @carlodicelico, @digitalsadhu, @Dreitser, @dylants, @finnp, @fmoliveira, @gaboesquivel, @gangstead, @gergelyke, @ghaiklor, @greelgorke, @jackvial, @jonotron, @keokilee, @krahman, @leonlin14, @LaughingSun, @llkats, @mikefrey, @pdjota, @ralucas, @rwilliamselab, @scmorrison, @sethvincent, @sintaxi, @tdd, @therebelrobot, @toolness, @usmantahirr, @vikene, @zo0o0ot.

**Comment by julianduque** [comment]
summoning @davsket

**Comment by afronski** [comment]
@michaelgrilo Both, May 16th and 23rd works for Silesia (Poland).

**Comment by asbjornenge** [comment]
May 17 is the [Norwegian Constitution Day](http://en.wikipedia.org/wiki/Norwegian_Constitution_Day). It's sort of a big deal. People might spend 16th travelling and preparing. So my vote goes to 23rd :+1:

**Comment by bajtos** [comment]
May 23rd works well for Czech Republic :+1:

**Comment by gergelyke** [comment]
May 23rd works for Hungary as well ;)

**Comment by greelgorke** [comment]
hmm. 23rd is the Saturday before Pentecost holiday in Germany. Because the following Monday is a holiday too its a traditional weekend for a short vacation trip. This day should work, though i'm not sure about it

**Comment by adambutler** [comment]
You could use something like http://doodle.com/ to work this out?

**Comment by cfsghost** [comment]
May 16 works for Taiwan!

**Comment by timoxley** [comment]
> @timoxley, if the International NodeSchool Day happens on May 16, are you likely to bypass that date and organize around CampJS V anyhow?

@michaelgrilo: Highly likely, though I was planning on running a pre-CampJS event here in Singapore to do a test run of the new workshoppers, perhaps this would coincide with that date.

Though now there's a possibility that CampJS will end up competing for attendees with any nodeschool day events in Australia – a venn diagram of the target audiences would look very circular.

**Comment by tdd** [comment]
Hey all,

May 16 works fine in France.

May 23 is just before Whit Sunday and Whit Monday, which means a lot of people use that 3-day span for family stuff, but NodeSchool prospective attendees don't usually pay much attention to this :smile: 

I'm pushing Mozilla Paris to host our first NodeSchool Paris this February, already have a few mentors rolled up, 'should be a 40-50 ppl affair.  I'd love to do another one early April, so the 3rd could match this International Day!

Cheers,

**Comment by sidorares** [comment]
It actually might be a good idea to have event one or two weeks before campjs in Melbourne. I have a feeling that most campjs attendees are more experienced than target nodeschool audience. We'll discuss that at next melbnodejs meetup

**Comment by rprieto** [comment]
@adambutler good idea. I created https://doodle.com/yc4qzpsw79u8ez3y if anyone wants to add what works well for a given country, or even individual availability to help out.

**Comment by timoxley** [comment]
> I have a feeling that most campjs attendees are more experienced than target nodeschool audience.

True, I guess it depends on which workshops you're running i.e. learnyounode vs learnuv.

I also just realised the brilliance of the name "learnuv". Good one @thlorenz.

**Comment by davsket** [comment]
Hello, yeah, May 23rd is a better date for Bogota! :smile:

**Comment by jonotron** [comment]
May 16th or May 23rd works for Kamloops, BC.

**Comment by hrayatnia** [comment]
may 16th for iran

**Comment by pdjota** [comment]
May 16th works for Montevideo

**Comment by iancrowther** [comment]
9 reg'd so far... pls continue to add to the form.  were starting to get closer to a date now I think

**Comment by iancrowther** [comment]
Feb 16th were running a nodeschool in London, but its also a good chance to get together and bounce some ideas.  ill be in the nodeschool/london gitter room for Q&A

**Comment by makenai** [comment]
May 16th would make me a little sad because it overlaps with Maker Faire in San Mateo. I like the 6th of May, or the 23rd.

**Comment by keokilee** [comment]
The 16th or 23rd works for Honolulu. We'll close it out for you guys!

**Comment by michaelgrilo** [comment]
While May 16 does have its fair share of fans, are we willing to concede victory to May 23?

**Comment by digitalsadhu** [comment]
Either is fine for christchurch but my vote is for May 23

**Comment by rprieto** [comment]
We have 9 replies on the [doodle](https://doodle.com/yc4qzpsw79u8ez3y) + quite a few informal votes here (it takes 5s to vote, no signup required). So far, looks like the 23rd is a winner.

**Comment by usmantahirr** [comment]
May 20 in Lahore PK

**Comment by vikene** [comment]
May 23rd works fine for chennai, india

**Comment by funkybaboon** [comment]
@kwakayama wanna do nodeschool stuttgart on one of these dates in may?

**Comment by iancrowther** [comment]
I have gone through my original form, the doodle and the comments and its clear that the community has gravitated to the 23rd.  Lets close this thread down and lock ink in that date

**Comment by kwakayama** [comment]
23rd May should work for Stuttgart.
@funkybaboon Thanks for pinging me.
Are you from stuttgart and want to mentor? join our [gitter chat](https://gitter.im/nodeschool/stuttgart)

**Comment by gangstead** [comment]
Just realized that May 23rd is memorial day in the US.  It's going to be very hard to get participation during a holiday weekend.  Is anybody willing to reconsider the date?

**Comment by max-mapper** [comment]
@gangstead good point, but I think it's gonna be hard to find a date that works for the whole world. Friday the 22nd in the US is the same time as Saturday in Asia/Pacific, so maybe if you can't do a weekend you could do it on a friday instead?
