### ISSUE TITLE
define & delegate tasks

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#23]
Hi All,

I have added [DELEGATED.md](https://github.com/nodeschool/international-day/blob/2015/DELEGATED.md) to the repo.  This file is meant as a record for who has taken ownership of specific tasks.

PLEASE can you contribute to this list add yourself where applicable.

Many Thanks

**Comment by iancrowther** [comment]
Is this referenced in the participating guide?

**Comment by Sequoia** [comment]
@grabbou did you want to take that "movie editing" slot?

**Comment by grabbou** [comment]
Yep. With @tomfrew we are heading that in #9.

**Comment by iancrowther** [comment]
merged DELEGATED with ORGANISERS
