### ISSUE TITLE
create microsite

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#3]

**Comment by iancrowther** [comment]
- dates, info and starting block!
- chapter enrolment form (gdocs maybe?)
- interactive map
- hangouts link
- gitter link
- details of high-five module
- details on adding members to an international-day list

**Comment by iancrowther** [comment]
github pages is alive.. need some colour now :-)

**Comment by michaelgrilo** [comment]
What is the link?

**Comment by max-mapper** [comment]
http://nodeschool.io/international-day/

**Comment by max-mapper** [comment]
for inspiration: http://opendataday.org/

**Comment by max-mapper** [comment]
did a first pass: http://nodeschool.io/international-day/

**Comment by iancrowther** [comment]
first pass is a good start, tweet it?

**Comment by Sequoia** [comment]
Nice max, thanks!
