### ISSUE TITLE
Who/Where in Italy? 

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/international-day#30]
There are two sign-ups for "Italy", one by @mcollina and one by @kylden without a mention of a city?! Where do you host it? Who is the host?

**Comment by kildem** [comment]
I live in Sardegna Cagliari, but I haven't found a location yet.
@mcollina is organizing the event in Milan.
http://www.mapcustomizer.com/map/nodeschool%20italy

**Comment by martinheidegger** [comment]
@kildem Thank you for the info! Will it be on Sardegna?

**Comment by kildem** [comment]
Yes, it should be on Sardegna.
but I'm not sure I'll be able to find a location for 23th May :(

**Comment by martinheidegger** [comment]
If pressing: use a cafe :wink:
