### ISSUE TITLE
Stop enrollment?

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/international-day#32]
@iancrowther Only few of the people that enrolled have actually created event sites and its already May 1st. It feels like there is only few time left to prepare the event. In order to not be bothered with updating the site and things for the latecomers I thought it might a good to stop enrollment and focus on working with the chapters that signed up?

**Comment by Sequoia** [comment]
FYI western mass is online-- sponsorship came thru so we're getting things rolling now (also I was busy preparing for ejs til last weekend).

**Comment by martinheidegger** [comment]
@Sequoia You have been signed up before. I am talking (about the) enrollment of new chapters.

**Comment by grabbou** [comment]
We are going live on Monday FYI. Preparations took a long time but finally all the things are done :)

**Comment by iancrowther** [comment]
@martinheidegger I completely agree with this.

Lets close enrolment on Friday 8th May by 18:00 GMT.

@maxogden - can you send out a tweet to this effect?

**Comment by martinheidegger** [comment]
https://twitter.com/leichtgewicht/status/595977874848419841
