### ISSUE TITLE
Update participating guide with stats requirment

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#35]

**Comment by martinheidegger** [comment]
We will first need someone to take care of it :)

**Comment by Sequoia** [comment]
Who is compiling all this data? _touches nose_ not it. :yum:

**Comment by iancrowther** [comment]
These are the metrics I can think of:
- Total Attendees
- Completed Workshops
- Hours of learning

@martinheidegger, @Sequoia can you expand?

We need a short blurb in the guide to ask chapter organisers to gather these metrics for a post day report.

**Comment by iancrowther** [comment]
we have crossover with https://github.com/nodeschool/international-day/issues/23 and [DELEGATED.md](https://github.com/nodeschool/international-day/blob/2015/DELEGATED.md)

**Comment by Sequoia** [comment]
@iancrowther I mean "who is **doing something with** all this data?" Unless there's a volunteer to handle the data I don't see the point in requiring* everyone to collect it.

\* let's remember no one's actually "required" to do anything wrt. nodeschool international day, everything is a request to voluntary participants.

**Comment by martinheidegger** [comment]
I would like to update the international-day site with the statistics showing what sort of event it was. Something like "2306 people from all over the world came together last year." It would help establishing the international day as the awesome thing it is ;)
