### ISSUE TITLE
Pre-international day organizer hack parties

### ISSUE THREAD

**Issue by max-mapper** [nodeschool/international-day#38]
Hey all, I had an idea today to do a couple short hack parties for the next 2 saturdays specifically for organizers:

For example, heres the one I'll be doing in PDX: https://github.com/maxogden/messages/issues/52

Example:

"
It will be at my house in SE Portland. I'll provide gigabit internet and snacks and we can hit up the food carts at 28th and Division close to my house for lunching.

Stuff to hack on:
- Stuff in the issue tracker: https://github.com/nodeschool/international-day/issues
- Writing new workshops for the event (e.g. `electron-workshop`)
- General community organizing brainstorming (e.g. https://github.com/nodeschool/international-day/issues/14)
- Planning a PDX event

"

Then I pinged individual organizers in my town to invite them. You can do it at your house or at a cafe/brewpub. Anywhere from 2-8 people is a good size, you don't need that many. The main idea is to get together and brainstorm to make sure the international day event is all set up.

**Comment by grabbou** [comment]
Nice one! @afronski - what about meeting all together next weekend to work on workshops and polish translations that are needed for few workshops? There are only two people here in Wrocław involved yet so no point in setting something up here if we can work in a bigger group.

**Comment by iancrowther** [comment]
Thanks an awesome idea :+1: 

I'll pencil in one for the 16th in London

**Comment by iancrowther** [comment]
@nodeschool/international-day anyone else available for this? Would be good to know what issues are being worked on so we don't duplicate effort

**Comment by iancrowther** [comment]
everyone who ran a hack day - you were awesome...
