### ISSUE TITLE
Two enrollments from Buenos Aires

### ISSUE THREAD

**Issue by afronski** [nodeschool/international-day#39]
Hi @a0viedo @nicolasard, there are two enrollments from Buenos Aires in Argentina in the #8 - is it the same event of a different ones?

If yes, please remove one of the comments at #8. Thanks! :smile:

**Comment by a0viedo** [comment]
Hey @afronski, I didn't noticed that! I already sent an email to @nicolasard and removed one of the comments. I think he confused the issue with registration for attending an event.  Thanks!

**Comment by afronski** [comment]
Thanks! :wink:
