### ISSUE TITLE
create high-five

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#4]

**Comment by iancrowther** [comment]
so @alanshaw and I were kicking around the idea of having a -g module that can post completed work shoppers to an api/endpoint which in turn creates a blip on a map on the microsite.  this could extended in any number of ways, but at its most basic, just pings to say joeblogs completed learnyounode at 12:34 in NYC

**Comment by iancrowther** [comment]
Im sure this has been discussed many times before :-)

**Comment by martinheidegger** [comment]
Yesterdays [great idea from @Atuyl](https://github.com/nodeschool/discussions/issues/864) would be awesome if it were to power the international day.

**Comment by iancrowther** [comment]
https://github.com/alanshaw/high-five

**Comment by iancrowther** [comment]
https://github.com/alanshaw/high-five-registry

**Comment by iancrowther** [comment]
im sure contribs are welcome

**Comment by iancrowther** [comment]
@alanshaw did you see ^^

**Comment by iancrowther** [comment]
closing as its in dev

**Comment by iancrowther** [comment]
shame this did not get done :-(
