### ISSUE TITLE
Poster for Promotion

### ISSUE THREAD

**Issue by finnp** [nodeschool/international-day#41]
Hey everyone,

@velchevski created a quick poster from the International Day banner for promoting the event. Hanging posters in cafes is a good way to reach people that wouldn't otherwise hear about NodeSchool.

Here is the source sketch file and the pdf, so you can customize them for your event, if you want:
https://github.com/nodeschool/berlin/blob/master/poster-international-day-2015.sketch
https://github.com/nodeschool/berlin/blob/master/poster-international-day-2015.pdf

And Here's how it looks like:
![poster](https://cloud.githubusercontent.com/assets/841788/7545099/4fc81546-f5d3-11e4-83dc-8ca0ada6541d.png)

**Comment by sudodoki** [comment]
@finnp Looks great! What are the fonts used?
In case someone need help, could help with sketch file editing/exporting, just ping me over gitter or mention here.

**Comment by finnp** [comment]
I think it's good old Helvetica.

**Comment by martinheidegger** [comment]
@finnp I like it. It would be awesome if it would use open fonts :)

**Comment by oleharland** [comment]
open fonts like google ones? It think helvetica is a good old font with good multi language support.

**Comment by martinheidegger** [comment]
@oleharland Yes, but if someone (like me) wanted to translate it to the local environment he/she would need to buy helvetica ...

**Comment by finnp** [comment]
I think you can safely use sans alternatives: http://theultralinx.com/2013/03/5-google-web-font-alternatives-helvetica-arial/

**Comment by iancrowther** [comment]
@finnp looks great.

Can you add this as a template to https://github.com/nodeschool/international-day/tree/2015/poster and close the ticket

ty
