### ISSUE TITLE
Homepage love needed

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/international-day#42]
Right now there are too many branches of two repos handing the display of the website of the nodeschool international day. Can someone give it a little love :wink:

**Comment by iancrowther** [comment]
+1 - this would be great to get some help with

**Comment by borellvi** [comment]
Which are the repos and branches which should be merged? These three maybe?
- https://github.com/nodeschool/international-day
- https://github.com/nodeschool/international-day/tree/gh-pages
- https://github.com/nodeschool/globe

**Comment by bcomnes** [comment]
Talking with @maxogden in pdx right now about this.

**Comment by bcomnes** [comment]
Thinking we should merge the globe into international-day and split down the middle with a flexbox.

**Comment by bcomnes** [comment]
I'm working on getting them merged now.  Hit me up on IRC if you want to collab.  #nodeschool on Freenode.

**Comment by bcomnes** [comment]
I'm going to do a few little experiments with a few ideas I have:
1. Copy over the assets to the international-day gh-pages
2. Iframe the globe maybe?
3. npm modularise things

**Comment by bcomnes** [comment]
I gave it a stab using flexbox, merged globe into international-day/tree/gh-pages, and turned http://nodeschool.io/globe into a redirect and message that points to http://nodeschool.io/international-day.

**Comment by bcomnes** [comment]
It even sorta works on mobile safari 
![](https://farm8.staticflickr.com/7719/17605941028_3fc67080b7_o.png)

**Comment by tdd** [comment]
Since the start it's looked terrible on a display such as Apple Cinema Display: the globe is way more faded out and yellowish, and way too far on the right, hence cut off. Just try it! :-1:

**Comment by bcomnes** [comment]
I would be :smile: to see anyone else dive in and make improvements directly as the rest of the week is super busy for me.

Here is just a little dump of random ideas it would be great to get done asap:
- [ ] Darken the globe to improve appearance on a wider set of monitors
- [ ] Add x2 assets for retina displays and wide screens.
- [ ] Add `<script src="//cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>` to head to fix safari flexbox issues.
- [ ] Improve globe layout on wide monitors.
  - Ideas: make the globe grow larger over certain window sizes?
  - Improve visual position?
  - Make the intro text sticky?

PR's and direct intervention encouraged!

**Comment by max-mapper** [comment]
@tdd looks fine on my machine. patch welcome :)

**Comment by tdd** [comment]
Hey Max,

That's right odd, screws up on both my employee's setup and mine.  Will 
def need to look into it, hopefully before Friday night!

## 

Christophe Porteneuve
tdd@tddsworld.com

**Comment by iancrowther** [comment]
A few chapters are missing still - London being one of them :-(

can we add a link to participating.md?

**Comment by bcomnes** [comment]
@iamchathu Can you link/post to details to this thread, or even better directly PR/push changes to https://github.com/nodeschool/international-day/blob/gh-pages/events.csv ?

**Comment by iancrowther** [comment]
were going to need to scrape the hello messages
