### ISSUE TITLE
Shirt

### ISSUE THREAD

**Issue by Sequoia** [nodeschool/international-day#44]
Does anyone have a shirt design worked out? I plan to get shirts for our "trainers" so we are easily identifiable (and as a momento of the event of course).

Currently my plan is just to scale the international day hex sticker up & stick it on a shirt, maybe putting "trainer" or something & maybe our chapter name and/or 2015 below, but if someone with an eye for design already has something like this laid out, I'd love to piggyback! :shirt: :globe_with_meridians: :ok_hand:

**Comment by grabbou** [comment]
We are making one but with our company logo somewhere (the only way to get a sponsorship). I would've needed to ask our designer about the progress and his ideas and will let you know tomorrow or on Tue, but I am happy to discuss another ideas.

**Comment by iancrowther** [comment]
can we put up two designs on http://teespring.com/

That way each chapter can buy what they need.

**Comment by iancrowther** [comment]
https://github.com/nodeschool/international-day/issues/15#issuecomment-95267127

**Comment by grabbou** [comment]
If they ship from US not sure if this can get delivered on time to Poland :(

**Comment by Sequoia** [comment]
Hm slapping nodeschool int'l logo on shirt actually prob. won't work because too many colors/print that big tends to get **hot** & be all... thick & hot & grubbly. I'll go a-begging to the Sticker thread & find out if someone can make a 2 or 3 color variant.

**Comment by Sequoia** [comment]
@grabbou :pray: ty for looking into this!!

**Comment by Sequoia** [comment]
@oleharland If it's not too much trouble, do you think you could make a 2 or 3 color variant of that sticker design suitable for printing on shirts? :pray: TYVM :pray: for your work on the design so far!!

**Comment by Sequoia** [comment]
Yo anyone who still wants to rush deliver, this is a pretty gr8 base for a shirt:
https://github.com/nodeschool/international-day/tree/2015/Stickers (/ht @maxogden)

This was my attempt http://www.bluecotton.com/share_display.html?u=1&s=1879054&x=1&r=9.06263673286052

**Comment by iancrowther** [comment]
nice

**Comment by Sequoia** [comment]
Ayyyy 😎✨👚💰
![image](https://cloud.githubusercontent.com/assets/317498/7735239/fb6d557a-ff09-11e4-9af7-44b3551107fd.jpg)
![image](https://cloud.githubusercontent.com/assets/317498/7735241/fb79b036-ff09-11e4-81d6-66d83be710c9.jpg)
![image](https://cloud.githubusercontent.com/assets/317498/7735240/fb7684a6-ff09-11e4-943e-819a0e2b1a88.jpg)

**Comment by max-mapper** [comment]
WHOA NICE!

**Comment by bcomnes** [comment]
Cool! Does it glow in the dark?

**Comment by Sequoia** [comment]
@bcomnes I wish! Just fluorescent I'm afraid :smile_cat:

**Comment by a0viedo** [comment]
niceee!

**Comment by iancrowther** [comment]
thats looks awsm.  how can people purchase said awsm?

can you add it to the participating.md so i can close the issue :-)
