### ISSUE TITLE
Looking for help running the day

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#45]
Hi,

I am looking for two members of the nodeschool community to help out with the "on the day" organising.

We have split the chapters into [4 blocks of timezones](https://github.com/nodeschool/international-day/blob/2015/ORGANISERS.md) and really need to identify two figure heads to help with the timezone when I'll be asleep.

The role would involve:
- Being a point of contact during your time slot
- Prompting chapters to record their intro videos
- Answering questions regarding [participation](https://github.com/nodeschool/international-day/blob/2015/PARTICIPATING.md)

Please get in touch if you can help out.

**Comment by a0viedo** [comment]
hey @iancrowther count me in. My plan was being able to contact as many chapters I can for that day.

**Comment by llkats** [comment]
I'm sorry to say that I don't have the bandwidth to take this on :/

**Comment by iancrowther** [comment]
@a0viedo - thank you

can you update https://github.com/nodeschool/international-day/blob/2015/ORGANISERS.md with your contact details

I have put you in for UTC -3 to UTC -6

:-)

**Comment by iancrowther** [comment]
@llkats - I completely understand..  Its a long day  

when you get 5, can you fill out the schedule with your start/end times :-)

**Comment by a0viedo** [comment]
@iancrowther done

**Comment by iancrowther** [comment]
we don't have an official owner for the USA so we will ask for a volunteer during the day
