### ISSUE TITLE
Update participating.md with recording steps

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#46]
Were going to use youtube live to record, download and commit intro videos.  

We need the [participating guide](https://github.com/nodeschool/international-day/blob/2015/PARTICIPATING.md#minifilm) to be updated to show people how.

**Comment by grabbou** [comment]
Speaking recording wise, @tomfrew is there any other solution worth considering that can provide good enough quality for the video? Would be cool to write down some tips like `avoid recording in a sun light` so no videos are rejected due to bad quality

**Comment by iancrowther** [comment]
@alanshaw @grabbou if you folks find a better way, please update the PARTICIPATING.md

**Comment by grabbou** [comment]
Well, there's already a guide in #9. I am going to add it to Participating.md
