### ISSUE TITLE
Google Hangout

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#48]
@Sequoia mentioned a desire to have an inter-chapter video link.

Can you setup a Google Hangout, ownership should change to each timezone contact during the day

**Comment by Sequoia** [comment]
No I cannot :smile_cat:. I am too busy organizing our local event & an all-day hangout would be disruptive/too much overhead. I think my idea for an international "chain" was a fun one but ultimately over-ambitious. I am planning to just coordinate with a couple other chapters for a morning & lunch-time hangout (I am excited to set up [local]morning chat with @grabbou in Poland!) & I encourage others to do the same. I think 1:1 self-organized connections is the most realistic approach here.

**Comment by Sequoia** [comment]
If someone wants to do this it's totes awesome but I cannot.

**Comment by grabbou** [comment]
@Sequoia, can you mail me at grabbou [ gmail ] so we can keep it a bit more organised? Kinda lots of things goin on here

**Comment by zhdzmn** [comment]
If everyone is still up for it let me try setting up one. I dont know who we will crossover from dhaka

**Comment by iancrowther** [comment]
we have setup a room for chapters to "hangout" 

https://appear.in/nodeschool

knock to join in and @iancrowther, @martinheidegger or @a0viedo will let you in :-)

if you want to record this, please use a screen recorder on your machine
