### ISSUE TITLE
Inter-chapter communication

### ISSUE THREAD

**Issue by jeduan** [nodeschool/international-day#49]
I love the idea of having a Hangout as a means of making the participants feel like they are part of a global movement, however, in my experience Hangouts between tech events are always awkward: it's incredibly easy to get audio feedback, and in the best of cases you are looking at a room full of people in chairs.

An approach I'd like to discuss is to incentivate people to tweet, upload pictures and videos stating their name, where they are from and the workshop they are having. That way we'd create a digital trail that we could easily get on stage to get people excited.

Thoughts?

**Comment by iancrowther** [comment]
Hey @jeduan,

Its a fair point, could you update the participating.md file to include a short guide and a hashtag?
