### ISSUE TITLE
decide on digital roll call mechanism

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#5]

**Comment by iancrowther** [comment]
so it would be great to list all participants on the microsite at the end of the day, a kind of "you made this possible" list

**Comment by iancrowther** [comment]
also, it would be cool to have some sort of event to event handover via hangouts or something - so each event group can high five and pass a "virtual batton"

**Comment by iancrowther** [comment]
i was thinking this could be via time zone, but there are soo many chapters in each timezone that the batton may just be multiple groups joining/leaving the hangout

**Comment by iancrowther** [comment]
can we record a 24hr hangout? would anyone volunteer to cut it down to a highlights reel?

**Comment by iancrowther** [comment]
i was thinking of creating a github team, but this is not scalable for each year and I doubt we want loads of teams eg i-d-2015, i-d-2016 with the same folks repeated..

any suggestions of how to build a rollcall thats got a super low barrier to adoption?

**Comment by jackvial** [comment]
Maybe you could create a "rollcall" issue on this repo and get everyone to leave a comment. Then use the github api to access the comments and update the list.

**Comment by gangstead** [comment]
For the Dallas meetups we have an attendance markdown list and members do pull requests to change that file.  This is hard to scale though as someone has to go through and accept dozens of PRs (which will be hundreds for Int'l day) and sometimes there are merge errors when two people modify the list at almost the same time.

**Comment by iancrowther** [comment]
@jackvial this seems the cleanest solution so far

@gangstead would be far to many PR's to manage

**Comment by gangstead** [comment]
@iancrowther I know, but it's great for the Github contribution graph!  We'll try the comment approach next month and see how it goes.

**Comment by iancrowther** [comment]
@gangstead we can de-centralise rollcall to each chapter owner, that would reduce the PR mgmt but rely on each owner completing the task.

I guess this would work as each attendee wants to be on the list, especially if we make a big deal out of it on the landing page.

the comments + api works so im still open..

I guess it depends on the appetite of each chapter owner...

**Comment by grabbou** [comment]
@iancrowther the Hangouts idea is awesome, I would really love to see live stream with other places so we can just see what's going on and stuff. The only issue might be the timezone but I am pretty sure we can find at least one hour where all of events will be ongoing.

**Comment by iancrowther** [comment]
I would just keep a single channel open for the 24 hours.  This could be a core part of the mini-film.

Do we have a script for this at all? can we ask around to see if anyone would like to take ownership?

I just added [PARTICIPATING.md](https://github.com/nodeschool/international-day/blob/2015/PARTICIPATING.md) in which we could ask each chapter to introduce themselves with a group cheer or something?

**Comment by tdd** [comment]
@iancrowther yes this ties in with my latest comment on #9 :wink: 

A roll call where every attendee / most attendees pitches in with a short quip sounds great, especially if we can broadcast it live in the venues. I for one could totally have it broadcast on a very large flat TV we otherwise use for presentations.  Perhaps a Hangout, IRC channel or some such would be enough. Or Gitter room?

**Comment by iancrowther** [comment]
https://github.com/nodeschool/international-day/blob/2015/PARTICIPATING.md#rollcall
