### ISSUE TITLE
Taipei

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/international-day#55]
http://nodeschool.kktix.cc/events/867150f7-0ae723

Seems like an event is organised completely out of the scope :) @nodeschool/taiwan Don't you want to join?

**Comment by iancrowther** [comment]
+1

**Comment by cfsghost** [comment]
Actually, that's organized by us. we really want to join. :-)

Here is discussion in Chinese:
https://github.com/nodeschool/taiwan/issues/8

**Comment by iancrowther** [comment]
https://github.com/nodeschool/international-day/issues/8#issuecomment-104728082
