### ISSUE TITLE
Social Media hashtag

### ISSUE THREAD

**Issue by a0viedo** [nodeschool/international-day#56]
I think it would be nicer to use an specific hashtag for this event rather than using #nodeschool only. This will help to separate tweets/posts during this particular event from other that took place before. Some suggestions:
- #nodeschool-international-day
- #nodeschool-international
- #nodeschool-int-day
- #nid

**Comment by max-mapper** [comment]
hmm all of those are kinda long (except the last one, which is too short :P)

**Comment by Sequoia** [comment]
#noodle-deschanel 🍝💁🏻
My $.02

**Comment by Sequoia** [comment]
It's an anagram

**Comment by a0viedo** [comment]
#nodeschool-day
#ns-day

**Comment by bcomnes** [comment]
What about just #nodeschool ?

**Comment by finnp** [comment]
I like #nodeschool.

**Comment by iancrowther** [comment]
+1 #nodeschool 

the content is short lived and needs to be simple to communicate :-)

**Comment by grabbou** [comment]
At our company, we are running a platform that shows images from a given hashtags in realtime on a screen (which is essentially a socket.io website) with optional white/black listing and moderation panel built-in (which can either pre or post moderate the content). The whole platform runs obviously on top of Node.js and EventEmitter using middlewares so if we need something else than built-in instagram/twitter, we can easily crack on it by the afternoon.

Might be worth investigating if that's something worth doing (see the whole NodeSchool world having fun!). 

What you think? Here's how it might look like (obviously we can show the tweet/instagram post content above the image and so on)

<a href="https://s3.amazonaws.com/f.cl.ly/items/3Z1m4719452r341N2I3z/Screen%20Shot%202015-05-20%20at%2000.02.50.png"><img src="http://f.cl.ly/items/0u0O2p183B0e3r0s0H2m/nodeschool.jpg"  /></a>

**Comment by max-mapper** [comment]
@grabbou yea thats a good idea! warning: I don't think we will look as stylish as the people in that screenshot though :P

If you make a page feel free to send a PR linking to it from this repo https://github.com/nodeschool/international-day

**Comment by iancrowther** [comment]
@grabbou can I close this issue?

**Comment by iancrowther** [comment]
hashtag is added to participating so closing

**Comment by grabbou** [comment]
I am reopening. I will close it as soon as the live link mentioned above is ready. ETA ~ 4 hours.

**Comment by iancrowther** [comment]
ah cool

**Comment by grabbou** [comment]
15 minutes.

**Comment by iancrowther** [comment]
shipped

**Comment by grabbou** [comment]
Oh yeah, just in case http://live.instabear.com/nodeschool Forgive me the weird domain :D
