### ISSUE TITLE
Hello from Osaka

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/international-day#62]
Dear Osakan's please say hello!

**Comment by martinheidegger** [comment]
Hello!

**Comment by dominhhai** [comment]
Hello!

**Comment by isawa138** [comment]
Hello!

**Comment by ixkaito** [comment]
Hello!

**Comment by kumatch** [comment]
Hello!!

**Comment by shimakyohsuke** [comment]
Hello!

**Comment by ria3100** [comment]
Hello!

**Comment by gonta616** [comment]
Hello!!

**Comment by sugitach** [comment]
Hi !!

**Comment by ultrakanji** [comment]
Hello!

**Comment by asan0** [comment]
Hello!

**Comment by kanizmb** [comment]
Hi :flags::sparkles:

**Comment by akspect** [comment]
Hello!!

**Comment by for21** [comment]
Hello!!!

**Comment by oldpetal** [comment]
Hello!!!

**Comment by goodseasons** [comment]
Hello!! ^^

**Comment by tomothumb** [comment]
Hello

**Comment by kodai0321** [comment]
Hi!

**Comment by syamgot** [comment]
Hello!

**Comment by AtuyL** [comment]
Hail, good citizen. :+1:

**Comment by yyaomail-git** [comment]
Hi, guys!

**Comment by SatoruMatsumoto** [comment]
Hello〜！

**Comment by TakuyaYamada** [comment]
Hello!

**Comment by masa-08** [comment]
Hello!!

**Comment by osser** [comment]
Hello!

**Comment by tdtsh** [comment]
Hi!

**Comment by martinheidegger** [comment]
皆様、昨日ありがとう！

**Comment by sugitach** [comment]
皆さん、お疲れさまでした。また、次回、よろしくお願いします。(^_^)ﾉ

SUGITA, Toshinori  / 杉田 敏典

**Comment by for21** [comment]
皆様お疲れさまでしたー！
初めてでしたが面白ろかったー！

Takashi Tokuda

2015年5月24日日曜日、SUGITA, Toshinorinotifications@github.comさんは書きました:

> 皆さん、お疲れさまでした。また、次回、よろしくお願いします。(^_^)ﾉ
> 
> SUGITA, Toshinori / 杉田 敏典
> sugitach@gmail.com <javascript:_e(%7B%7D,'cvml','sugitach@gmail.com');>
> 2015/05/24 午後9:13 "Martin Heidegger" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
> 
> > 皆様、昨日ありがとう！
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/nodeschool/international-day/issues/62#issuecomment-105008311>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/international-day/issues/62#issuecomment-105010836
> .

## 

# 

KEIGAN 德田貴司
for21.rakuten@gmail.com
mobile: 080-3866-6399

# （HP移行中）http://sftfapp.blogspot.jp/
