### ISSUE TITLE
Hello from Lisbon

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#66]

**Comment by sericaia** [comment]
Hello from Lisbon! :dancer: 

Let's do it!

**Comment by iled** [comment]
Hello from Lisbon!

I'm taking this chance to learn JS and node.js :)

**Comment by foliveira** [comment]
Hi from Lisbon! :tada:

**Comment by zcarlos** [comment]
Hi from Lisbon I'm from Coimbra.

**Comment by nneves** [comment]
Hello from Lisbon \0/

**Comment by ghost** [comment]
Hello from Lisbon \o

**Comment by JSFernandes** [comment]
Big hello from Lisbon!

**Comment by ghost** [comment]
Hello From Lisbon, sorry for the delay
