### ISSUE TITLE
create an event sticker

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#7]

**Comment by finnp** [comment]
Would love to have a cool sticker, would want to order them soon.

Maybe we can have one with a globe in the middle, inspired by [this](https://github.com/nodeschool/international-day/issues/10#issuecomment-88163460)? Or maybe a big signpost pointing to various participating cities.

@oleharland @SleepWalker You both created cool NodeSchool stickers for your local chapters. Could you help out create a cool one for the international nodeschool day?

@martinheidegger @naranjitagolden @jeduan You added cool NodeSchool stickers to the hexdex. Could you point the person who designed them here? Or if you designed them, help out create an awesome event sticker?

**Comment by oleharland** [comment]
hello,

i have some things to do right now but i can think about it in the next days. 

Do you already have a color scheme and do you want the globe? I think it should be simple and easy to recognise that the event is a global event.

You said you want to print them soon. Do you already have dates/deadlines?

**Comment by finnp** [comment]
@oleharland Hey, awesome. The sticker is actually no that urgent though. The event is may 23rd, so I think 23rd of April is a good deadline for the logo, so we have a month of using it for promotion and enough time to order stickers. Earlier would be awesome though.

I would love to have the globe. Maybe somehow in connection with elements from the nodeschool logo: http://nodeschool.io/images/schoolhouse.svg . (Maybe a nodeschool building on top of a globe?)

The color scheme is not fixed yet. I would like it to be different from the general homepage (nodeschoo.io). Maybe you could suggest something and we could adopt the website accordingly then? I kind of like the minimal design the website has right now: http://nodeschool.io/international-day/

**Comment by oleharland** [comment]
Now here in the right place:
Last night some i did some first scribbles with colors and how it could be build. Not really happy yet with it...
![screen shot 2015-04-14 at 15 24 36](https://cloud.githubusercontent.com/assets/573554/7137503/8c7048b4-e2ba-11e4-9bca-a47e0c356793.png)

**Comment by finnp** [comment]
I love the idea with the hexagon globe. However I think the big globe on the right, looks generally more appealing.

**Comment by oleharland** [comment]
@finnp the globe (left) does not fit really good into the hexagon and it also should be more eye-catching. the right ones should the way to go

**Comment by martinheidegger** [comment]
@oleharland I like the one on right most.

**Comment by samiconductor** [comment]
There's also a sticker swap (https://github.com/nodeschool/organizers/issues/182) we could all participate in. We'd end up with a cool patchwork much like the [international day landing page](http://nodeschool.io/international-day/).

**Comment by max-mapper** [comment]
@oleharland i LOVE that globe. can you share a SVG? or better yet send a PR to http://hexb.in/ :)

**Comment by a0viedo** [comment]
@oleharland awesome! +1 to the one on the right

**Comment by oleharland** [comment]
@maxogden you mean the left one or right one? So I want to finalize it first and then I will upload it here as svg for web use and I could make a blueprint for the sticker printing.

**Comment by max-mapper** [comment]
@oleharland the one on the right, sorry (with the green and blue)

**Comment by marulango** [comment]
So, @jeduan pointed me here this morning.
I had a lot of stuff to compile today, so while I was waiting I worked on refined versions of @oleharland concepts. 
I tried with both the hexagon globe and the background one. At some point, it reminded me of space mission patches.

![screen shot 2015-04-14 at 6 01 23 pm](https://cloud.githubusercontent.com/assets/3750189/7149275/03152f6e-e2d1-11e4-8270-4493aff0b995.png)

**Comment by max-mapper** [comment]
![](http://media.giphy.com/media/rRj2n8dXxB7xu/giphy.gif)

**Comment by SomeoneWeird** [comment]
Those are awesome!

**Comment by oleharland** [comment]
@bleendingxedge i like the stars! But the nodeschool slogan is also flying around

i will see if i could do a new version today

**Comment by oleharland** [comment]
Hello again,

i liked the colors of @bleedingxedge the deepspace in the mid and the gold border outside. So i copied that in my layout with the cool stars. I made the Nodeschool line bigger that the typography got more stability and sticked to my perspective of the globe like the atmospheric pictures. I also added as little feature a hexagon satelite to avoid to much blank space.

![nodeschool-globalevent](https://cloud.githubusercontent.com/assets/573554/7160188/c1cdc644-e387-11e4-93a5-36584ed041bd.png)

**Comment by max-mapper** [comment]
@oleharland super cool, I like the collaboration that is happening in this thread. Hexagon sputnik is a nice touch too. And I also think your latest iteration is well balanced.

@oleharland @bleedingxedge would you mind sharing AI files or vector versions when you feel good about them? I wanna get these out to organizers so they have enough time to print them

**Comment by finnp** [comment]
I love it!

**Comment by marulango** [comment]
@oleharland :open_mouth: :+1: I'm loving the satellite.
And yes, reading is much more clear and makes more sense to the atmospheric pictures. Maybe some minor touchups like size/distribution of the elements, but I'm loving it.

**Comment by oleharland** [comment]
@bleedingxedge thank you!

In general i will put up here the AI tomorrow, that you can print them and share it on webpages.

**Comment by llkats** [comment]
:heart_eyes: :heart_eyes: :heart_eyes: :+1: :+1: :+1:

**Comment by jedireza** [comment]
:boom: :+1:

**Comment by SleepWalker** [comment]
good sticker! :+1:

**Comment by martinheidegger** [comment]
I have been told that https://hexi.pics/ will provide an english interface soon to order your stickers online globally.

**Comment by iancrowther** [comment]
@martinheidegger any dates on this?

**Comment by iancrowther** [comment]
@oleharland it really is a fantastic sticker..

**Comment by martinheidegger** [comment]
Soon (likely next week ...)

**Comment by iancrowther** [comment]
oh, thats great news.. :-) +1

**Comment by martinheidegger** [comment]
Oh! It is available internationally, cheers!

**Comment by finnp** [comment]
It's already available here: https://hexi.pics/items/aa621a0d29b88cab04f188aeb98788a9

**Comment by martinheidegger** [comment]
@iancrowther This can be closed right? So should be mentioned somewhere.

**Comment by grabbou** [comment]
@afronski are you going to order the stickers from hexi or print them in Poland? We are going to order few of them here, in Wrocław, so been thinking we might get a discount for a bigger order or something?

**Comment by afronski** [comment]
@grabbou We ordered two months ago a couple sheets, but definitely we need to order another. We didn't use _hexi_ before, we printed them in Poland - ping me on _priv_, we will work something out.

**Comment by Sequoia** [comment]
where did the SVG for this end up? hexi.pics is super expensive for me here in US compared to US vendors and shipping info is unclear (i.e. hexipics is not an option for me)

**Comment by max-mapper** [comment]
@Sequoia https://github.com/nodeschool/international-day/tree/2015/Stickers

**Comment by Sequoia** [comment]
thx!
