### ISSUE TITLE
Hello from Dhaka

### ISSUE THREAD

**Issue by az7arul** [nodeschool/international-day#70]

**Comment by faisalhmohd** [comment]
Hey!

**Comment by Nahal-Islam** [comment]
Hi

**Comment by SdShadab** [comment]
Hey everyone!

**Comment by amuntasim** [comment]
Hello from Dhaka!

**Comment by ishtiaque23** [comment]
Hello!

**Comment by imranfarid** [comment]
Hi

**Comment by hsleonis** [comment]
Hello :)

**Comment by shafayeatsumit** [comment]
hello.

**Comment by naimrajib07** [comment]
Hello guys ;)

**Comment by NerdFaisal404** [comment]
Hey Awesome people Awesome  event :)

**Comment by ghost** [comment]
Howdy!

**Comment by FuadRafiq** [comment]
Hi.... enjoying the meetup....

**Comment by salimerid** [comment]
i was there .... they provided nice burger ... next time i will come for node and burger...

**Comment by tanvirraj** [comment]
Hola !!

**Comment by mkawsar** [comment]
Hello

**Comment by selimppc** [comment]
Good Day !

**Comment by mones-cse** [comment]
ola bros

**Comment by mahsin-islam** [comment]
Hi !! console.log("hello");

**Comment by ghost** [comment]
having fun with noders! :)

**Comment by faizaalam** [comment]
Hey!! :D

**Comment by zhdzmn** [comment]
olo :)

**Comment by prappo** [comment]
hi

**Comment by newazsharif** [comment]
Hello guys...... :)

**Comment by junan** [comment]
hello!

**Comment by ProsantaChaki** [comment]
Hi  
I am feeling awesome with all of you .

**Comment by bleedingpoem** [comment]
Hello! NodeSchool..........

**Comment by mofrubel** [comment]
hello :)

**Comment by zisuzon** [comment]
hey everyone..... :)

**Comment by imranabdurrahim** [comment]
hmm

**Comment by jeebon** [comment]
Hey, it's awesome,  best wish for nodejs team....

**Comment by azmul** [comment]
Hi ,
i am so much happy and felling awesome with Newscread and Node.js

**Comment by prio101** [comment]
some crazy quote ... I missed my fries .... and yes ... I don't mind ... node is also crispy .... and yes .... node is alone enough to hold me on screen

**Comment by mamunsse** [comment]
Hello!!!..... having lot's of fun with all noders with gd food at #newscreed

**Comment by raihantaher** [comment]
Node.js Rocks!!

**Comment by mamunsse** [comment]
Hello!!!..... having lot's of fun with all noders with gd food at #newscreed

**Comment by faequl** [comment]
hello

**Comment by sam412** [comment]
it was a great experience with nodeschool.

**Comment by aplmhd** [comment]
Welcome to NodeSchool World!
"Hello NodeSchool !l"

**Comment by riyadhalnur** [comment]
Hello good people!!

**Comment by az7arul** [comment]
Hello noders

**Comment by Nahal-Islam** [comment]
hello

**Comment by prio101** [comment]
Thanks !!!! I am amazed ...
