### ISSUE TITLE
Hello from Chang Mai

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#71]

**Comment by ghost** [comment]
Hey there :+1:

**Comment by iancrowther** [comment]
pls add your attendees :-)

**Comment by armno** [comment]
hi there! :beers:

**Comment by aikordek** [comment]
yo :)

**Comment by meeDamian** [comment]
Warm (and rainy) welcome from Chiang Mai ;)

**Comment by jengguru** [comment]
Sup Chiang Mai peeps!

**Comment by aimmango** [comment]
Sawasdee ka.  Good evening from Chiang Mai! 
![img_8930](https://cloud.githubusercontent.com/assets/12167702/7783761/cd9013de-0177-11e5-98df-7083364f8dc8.JPG)
![img_8931](https://cloud.githubusercontent.com/assets/12167702/7783762/cd91799a-0177-11e5-8510-b62f3c45e232.JPG)
![img_8932](https://cloud.githubusercontent.com/assets/12167702/7783763/cd92a0f4-0177-11e5-9082-cd361495b123.JPG)

**Comment by iancrowther** [comment]
:-)

**Comment by rburns** [comment]
helloๆ
