### ISSUE TITLE
Hello from Paris

### ISSUE THREAD

**Issue by tdd** [nodeschool/international-day#73]
Hi all!  Sorry, we launched an hour ago, had skipped this!

Les participants du jour : commentez ici !

**Comment by jmpp** [comment]
Hello from #NodeSchoolParis ! We're going to play with Piratebox and node :)

**Comment by nerik** [comment]
:beers:

**Comment by martinjeannot** [comment]
console.log('Hello MONDE'); // Christophe has unmatched skills in english :D

**Comment by supertanuki** [comment]
Bonjour ! Hello ! Kaw ou fè ? Marhaba !

**Comment by alain75007** [comment]
Hello from #NodeSchoolParis ! ,  Too COOOOOOOOOOOOOLLLLLL

**Comment by UnbearableBear** [comment]
HELLO FROM PAAAAARIIIIIS

**Comment by marie-ototoi** [comment]
Hello from Paris !

**Comment by donaminos** [comment]
Great to be here #NodeSchoolParis

**Comment by stephane71** [comment]
Hello from Mozilla Paris!

**Comment by alain75007** [comment]
Code for breakfast at #nodeschoolparis

**Comment by rumesh** [comment]
Hello from #mozillaParis #NodeSchoolParis !

**Comment by sophietk** [comment]
Hi guys, happy to be here with you :)

**Comment by Andromed** [comment]
Hello ! Ready for NodeJS !!! :)

**Comment by iteuss** [comment]
Heeey :) Happy to be here with you

**Comment by arnaudbreton** [comment]
Bonjour !! So cool to see the Node community growing all around the World. Proud to help new comers. Enjoy!

**Comment by alexandreferreirafr** [comment]
Hello :)

**Comment by ghost** [comment]
Hello world

**Comment by fagossa** [comment]
Glad to be here :)

**Comment by yassinedoghri** [comment]
Hey everyone!

**Comment by yanning92** [comment]
hi, happy to be participate

**Comment by y9mo** [comment]
hello from paris. ready to tackle Nodejs!!!!!!!!!!!!! ;)

**Comment by csu6** [comment]
Youpiiiiii !!!

**Comment by micabe** [comment]
Hello from paris

**Comment by dicaormu** [comment]
salut!!

**Comment by ghost** [comment]
Hi from Paris !

**Comment by dylaw** [comment]
Hey hi yo !! from Paris ... (^.^)

**Comment by pepinpin** [comment]
Hi all, let's ruuuuuuumble !!!

**Comment by hmore** [comment]
hellooooo !

**Comment by masterct** [comment]
S'up everybody! Happy to be here at  #mozillaParis for the #NodeSchoolParis day!! :smiley:

**Comment by jpbanchon** [comment]
aloha !

**Comment by tdd** [comment]
All Paris attendees: you can come in and chat with other attendees the world over at https://gitter.im/nodeschool/international-day

**Comment by MarionChimiack** [comment]
Let's get this party started #NodeSchoolParis #MozillaParis

**Comment by JeremiePat** [comment]
Hi! :)

**Comment by yanncheriet** [comment]
console.log('Hello world!');

**Comment by planeth44** [comment]
Nice to be here in gorgeous Mozilla hotel :)

**Comment by DjebbZ** [comment]
Hello everyone, happy to be mentoring in Paris today :)
