### ISSUE TITLE
Enrollment

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#8]
We need to set up an enrolment process.

What I think I need:
- Chapter Name
- Chapter Contact
  - github username
  - skype username

I would like to manage this via github as we are already here.

Any thoughts/suggestions?

**Comment by mcollina** [comment]
Milan, Italy
Matteo Collina
Github: @mcollina
Email: matteo.collina@gmail.com

**Comment by gangstead** [comment]
Dallas (Texas), USA
Steven Gangstead
Chapter: http://nodeschool.io/dallas
Github: @gangstead
Email: steven@gangstead.com
Twitter: gangstead
Skype: steven.gangstead

**Comment by afronski** [comment]
Katowice (Silesia), Poland
Wojtek Gawroński
Chapter: https://nodeschool.io/silesia
Github: @afronski
Email: afronski [at] gmail
Twitter: afronski
Skype: afronski

**Comment by No9** [comment]
Dublin, Ireland
Anton Whalley
Github: @no9
Skype: Bass11Dark

**Comment by iancrowther** [comment]
ok this works :-)

**Comment by hrayatnia** [comment]
Iran
Amir hesam Rayatnia
Github: @hrayatnia 
Skype: rayatnia
Email: h.rayatnia@gmail.com

**Comment by Sequoia** [comment]
Western Massachusetts (MA), USA
Sequoia McDowell
Chapter: https://github.com/nodeschool/western-mass/
Github: @sequoia 
Skype: sequoia.mcdowell 
Email: sequoia.mcdowell@gmail.com

Note: Want to mostly listen & see if I can sync an event to the global date, don't plan to contribute a bunch to global planning (but it looks like there are plenty of planners already luckily!). :smile_cat:

**Comment by martinheidegger** [comment]
Osaka, Japan
Martin Heidegger
Email: martin.heidegger [at] gmail
GitHub: @martinheidegger 
Skype: mastakaneda

**Comment by jasonrhodes** [comment]
[no-enroll] What does this enrollment mean, specifically?

**Comment by iancrowther** [comment]
[no-enroll] @jasonrhodes it just means means you have committed to take part in the day.  We are kicking the idea of a virtual baton to pass between chapters so we need to know how to contact each chapter as the day progresses

**Comment by makenai** [comment]
Las Vegas (Nevada), USA
Pawel Szymczykowski
Chapter: http://nodeschool.io/vegas
Github: @makenai 
Email: makenai [at] gmail.com
Skype: makenaizo

**Comment by bajtos** [comment]
Hradec Králové, Czech Republic
Miroslav Bajtoš
Chapter: http://nodeschool.io/hradec-kralove/
Github: @bajtos

**Comment by julianduque** [comment]
Medellín, Colombia
Julian Duque
Chapter: https://github.com/nodeschool/medellin
Github: @julianduque 
Email: julianduquej@gmail.com
Skype: julian.shemtov

**Comment by carlodicelico** [comment]
Portland Maine https://nodeschool.io/Portland-me

**Comment by fforres** [comment]
Santiago, Chile
Felipe Torres Sepulveda
Chapter: http://www.noders.cl
Email: felipe.torressepulveda@gmail.com
Twitter: fforres
Skype: forres.ftorres
Github:forres

**Comment by jeduan** [comment]
Mexico City, Mexico
Jeduan Cornejo
Email: jeduan [at] gmail.com
Chapter: http://nodeschool.io/mexicocity
Github: jeduan
Skype: jeduan

**Comment by asbjornenge** [comment]
[no-enroll] [cancelled]
Stavanger, Norway
Asbjorn Enge
Chapter: https://github.com/nodeschool/stavanger
Email: asbjorn@hanafjedle.net
Github: @asbjornenge
Skype: asbjornenge

**Comment by blakmatrix** [comment]
Seattle (WA), USA
Farrin Reid
Email: blakmatrix [at] gmail
Chapter: https://github.com/nodeschool/seattle 
Github: @blakmatrix

**Comment by keokilee** [comment]
Honolulu (Hawaii), USA
George Lee
Email: keoki.lee [at] gmail
Chapter: https://github.com/nodeschool/honolulu
Github: @keokilee
Twitter: keokilee

**Comment by davyengone** [comment]
Brussels, Belgium
Davy Engone
Email: davy [at] philos.io
Github: @davyengone

**Comment by jonotron** [comment]
Kamloops, Canada
Jonathan Bowers
Chapter: https://github.com/nodeschool/kamloops
Email: jonotron [at] gmail
Github: @jonotron 
Twitter: thejonotron

**Comment by a0viedo** [comment]
Buenos Aires, Argentina
Alejandro Oviedo
Chapter: https://github.com/nodeschool/buenosaires
Github: @a0viedo 
Email: alejandro.oviedo.g@gmail.com
Skype: alejandro.og

**Comment by yoshuawuyts** [comment]
[no-enroll] [cancelled]
Amsterdam, Netherlands
Yoshua Wuyts
Chapter: https://github.com/nodeschool/Amsterdam
Github: @yoshuawuyts 
Email: i@yoshuawuyts.com
Skype: yoshomfg

**Comment by grabbou** [comment]
Wrocław, Poland
Mike Grabowski
Chapter: https://github.com/nodeschool/wroclaw
Github: @grabbou 
Email: grabbou [at] gmail
Skype: grabbou

**Comment by ralucas** [comment]
Boulder (Denver), USA
Richard Lucas
Chapter: https://github.com/nodeschool/denver-boulder
GitHub: @ralucas 
Email: richard@richardalucas.com
Skype: rlucas130

**Comment by usmantahirr** [comment]
Lahore, Pakistan
Usman Tahir
Github: @usmantahirr 
Email: ch.usman.tahir [at] gmail
Skype: ch.usman.tahir

**Comment by timmarinin** [comment]
[no-enroll] [cancelled]
Saint Petersburg, Russia
Marinin Tim
Chapter: http://nodeschool.io/spb
Github: @marinintim
Skype: marinintim
Email: marinintim [at] gmail

**Comment by kildem** [comment]
Italy
Contact: ildehouse@gmail.com
Skype: kylden

**Comment by sericaia** [comment]
Lisbon, Portugal
Daniela Borges
Chapter: https://github.com/nodeschool/lisbon
Github: @sericaia
Skype: sericaia

**Comment by timoxley** [comment]
Melbourne, Australia ([CampJS](http://campjs.com/))
Tim Oxley
Email: secoif@gmail.com
GitHub: @timoxley
Skype: secoif

**Comment by finnp** [comment]
Berlin, Germany
Finn Pauls
Email: derfinn@gmail.com
Chapter: http://github.com/nodeschool/berlin
github: @finnp 
twitter: finnpauls
skype: finn-hat-skype

**Comment by tdd** [comment]
Paris, France
Christophe Porteneuve
Email: tdd@tddsworld.com
Chapter : http://nodeschool.github.io/paris/
GitHub: @tdd
Skype: tddian

**Comment by pricco** [comment]
Montevideo, Uruguay
Pablo Ricco
Chapter : http://nodeschool.github.io/montevideo/
GitHub: @pricco
Email: pricco@gmail.com
Skype: pricco82

**Comment by gaboesquivel** [comment]
San Jose, Costa Rica
Gabo Esquivel
Chapter: https://github.com/nodeschool/costarica
Github: @gaboesquivel
Skype: gaboesquivel

**Comment by lvivier** [comment]
Vancouver, Canada
Luke Vivier
Email: luke@vivier.ca
Chapter: https://github.com/nodeschool/vancouver
GitHub: @lvivier
Skype: lukevivier

**Comment by llkats** [comment]
San Francisco (California), USA
Lydia Katsamberis
Chapter: http://www.nodeschool.io/sanfrancisco
Github: @llkats
Skype: llkats

**Comment by awaterma** [comment]
Bainbridge Island (WA), USA
Andrew Waterman
Email: awaterma@awaterma.net
Chapter: http://islandjs.org
Github: @awaterma
Skype: andrew.waterman

**Comment by martinheidegger** [comment]
[no-enroll] Please make sure you read the https://github.com/nodeschool/international-day/blob/2015/PARTICIPATING.md docs

**Comment by colinloretz** [comment]
Reno (Nevada), USA
Colin Loretz
Chapter: http://nodeschool.io/reno
Github: @colinloretz
Skype: colinloretz

**Comment by paulohp** [comment]
Belo Horizonte, Brazil
Paulo Pires
Chapter : http://nodeschool.io/belo-horizonte/
GitHub: @paulohp
Email: tarallo.php [at] gmail
Skype: paulo.manguara

**Comment by spikeheap** [comment]
Oxford, UK
Ryan Brooks
Chapter: http://jsoxford.com
Github: @spikeheap
Skype: ryan.p.brooks

**Comment by alexfernandez** [comment]
Madrid, Spain
Alejandro Fernández
GitHub @alexfernandez
Email alexfernandeznpm [at] gmail
Skype: chenno

**Comment by jeffjewiss** [comment]
Toronto, Canada
Jeff Jewiss
Email: jeffjewiss [at] gmail
GitHub: @jeffjewiss
Skype: jeffjewiss

**Comment by yosuke-furukawa** [comment]
Tokyo, Japan
Yosuke Furukawa
GitHub @yosuke-furukawa
Email: yosuke.furukawa [at] gmail
Skype: yosuke_furukawa

**Comment by beltran-rubo** [comment]
Seville, Spain
Beltran Rueda
GitHub: @beltran-rubo
Twitter: beltranrubo
Skype: beltranrubo

**Comment by ghost** [comment]
Provo (Utah), USA
Michael A. Jackson
GitHub: @majgis
Chapter: http://nodeschool.io/provo
Email: majgis [at] gmail
Event: http://meetu.ps/2J6W23

**Comment by kwakayama** [comment]
Stuttgart, Germany
Kentaro Wakayama
Chapter: http://nodeschool.io/stuttgart/
github: @kwakayama 
twitter: wakayamakentaro
Email: kentaro@wakayama.io

**Comment by chitopolo** [comment]
Cochabamba, Bolivia
Rene Polo
Chapter: https://github.com/nodeschool/cochabamba
Github: @chitopolo 
Email: renejpolo@me.com
Skype: chito_polo
Twitter: @chitopolo

**Comment by diegowifi** [comment]
Monterrey, México
Diego Ponce
Github: @diegowifi
Email: diegoponce [at] outlook.com
Chapter: http://nodeschool.io/mty
Skype: d1360_ponce

**Comment by cronopio** [comment]
Pereira, Colombia
Daniel Aristizabal
Github: @cronopio
Email: aristizabal.daniel@gmail.com
Skype: cronopio40

**Comment by nicolasard** [comment]
Buenos Aires, Argentina
Nicolas Ardison
Github: @nicolasard
Email: nicolas.ard@gmail.com
Skype: nicolas.ard@outlook.com

**Comment by ryanramage** [comment]
Edmonton (Alberta), Canada
Ryan Ramage
github: @ryanramage
Email: ryan.ramage [at] gmail

**Comment by max-mapper** [comment]
[no-enroll] Hey all, I recommend you have a small hack party for organizers in the next couple of weeks leading up to your main event. I made an issue with more details here: https://github.com/nodeschool/international-day/issues/38

**Comment by gmauricio** [comment]
Manizales, Colombia
Germán Mauricio Muñoz
Github: @gmauricio
Email: gmauricio.munoz at gmail
Skype: gmauricio

**Comment by az7arul** [comment]
Dhaka, Bangladesh
Azharul Islam
github: @az7arul
Email: az7arul@gmail.com
skype: az7arul

**Comment by martinheidegger** [comment]
[no-enroll] Closing issue as the enrollment ended.

**Comment by iamchathu** [comment]
Colombo, Sri Lanka
Chathu Vishwajith
github: @iamchathu
email: 4evercreations [at] gmail
skype: chathuranga_surath

**Comment by ghost** [comment]
Chiang Mai, Thailand
Amine Mouafik
Github: @kytwb
Skype: amine.mouafik

**Comment by martinheidegger** [comment]
[no-enroll] @kytwb Please know that you are late and we are trying to collect event pages now! https://github.com/nodeschool/international-day/issues/22

**Comment by ghost** [comment]
[no-enroll] @martinheidegger yeah, I'll make sure our chapter is up-to-date by today.

**Comment by iancrowther** [comment]
[no-enroll] @kytwb @iamchathu please add your details to the [schedule](https://github.com/nodeschool/international-day/blob/2015/international-nodeschool-schedule.csv) once you have your event page live.

**Comment by iancrowther** [comment]
[no-enroll] @nodeschool/international-day pls can everyone review the [schedule](https://github.com/nodeschool/international-day/blob/2015/international-nodeschool-schedule.csv) and fill in the blanks :-)

**Comment by Sequoia** [comment]
[no-enroll] Are those times local times or GMT?

**Comment by martinheidegger** [comment]
[no-enroll] UTC (not GMT) with a UTC mention beside.

**Comment by max-mapper** [comment]
Portland (Oregon), USA
Max Ogden
GitHub: @maxogden
Chapter: http://nodeschool.io/pdx
Email: mogden @ gmail
Event: http://calagator.org/events/1250468498

**Comment by iancrowther** [comment]
[no-enroll]
hey @maxogden 

can you add Portland to the [schedule](https://github.com/nodeschool/international-day/blob/2015/international-nodeschool-schedule.csv)

**Comment by martinheidegger** [comment]
Santa Marta, Colombia
Pedro E. Romero
Chapter: http://nodeschool.io/santamarta
Github: @pedroromn
Email: pedroromn@gmail.com
Twitter: @peyorom
Event: https://www.eventbrite.com/e/nodeschool-santa-marta-2014-tickets-14415524221

**Comment by iancrowther** [comment]
Taipei, Taiwan
Fred Chien
Github: @cfsghost 
Email: cfsghost@gmail.com
Event: http://nodeschool.kktix.cc/events/867150f7-0ae723

**Comment by iancrowther** [comment]
London, UK
Ian Crowther
Chapter: https://github.com/nodeschool/london
Github: @iancrowther
Twitter: @iancrowther
Skype: iancrowther1

**Comment by shime** [comment]
Varaždin, Croatia
Hrvoje Šimić
Chapter: https://github.com/nodeschool/zagreb
Github: @shime
Twitter: [shimetweets](https://twitter.com/shimetweets)

**Comment by iancrowther** [comment]
@nodeschool/international-day 

I am requesting all mini-films be uploaded and links provided by Friday 12th June

**Comment by iancrowther** [comment]
PLEASE can you upload and photos/video of the day here https://drive.google.com/folderview?id=0B1E3fBFiidMXS2txV0N2ejVKNjg&usp=sharing

Also chapter logos if they exists
