### ISSUE TITLE
Gather mini-film video/photo/logo

### ISSUE THREAD

**Issue by grabbou** [nodeschool/international-day#86]
Hey guys,
Where shall we update the mini-film things we've done as per Participating.md? We've recored a "We love Nodeschool" in Polish + some videos of people coding.

**Comment by max-mapper** [comment]
Put them on youtube under hashtag #nodeschool, we can always re-download them

**Comment by iancrowther** [comment]
https://github.com/nodeschool/international-day/tree/2015/Video 
- points for making the 1st commit :-)

**Comment by iancrowther** [comment]
participating.md doc asks each chapter to commit their videos.  Adding to youtube is a good call also, but we want the assets gathered so we can edit them later

**Comment by max-mapper** [comment]
Ah makes sense. If the video is >100MB it won't fit in Git, so I guess in
that case at least put on youtube so we can access em :)

**Comment by iancrowther** [comment]
:bulb: good point :-p

**Comment by grabbou** [comment]
We can give you FTP credentials. I think it makes sense to put them in a place where we can easily download them to make the video :)

**Comment by sethvincent** [comment]
seattle video shots here: https://www.youtube.com/playlist?list=PLtqV0D_WhsDkeaLIDMJ2mm288psaVY4IM

they should be tagged as nodeschool, too.

**Comment by roughpandaz** [comment]
@grabbou  Cool! so I guess you don't want us to do any editing?

**Comment by grabbou** [comment]
@RongxinZhang Well, you can, but I think our team would've prefer to get the raw versions as I think that matters when editing them all together :)

**Comment by grabbou** [comment]
@sethvincent thanks! awesome stuff!

**Comment by teomurgi** [comment]
https://github.com/nodeschool/international-day/tree/2015/Video results in 404 right now

**Comment by roughpandaz** [comment]
Vancouver YVR
https://youtu.be/so4z2sYFe0Y

**Comment by martinheidegger** [comment]
@RongxinZhang "This video is private"

**Comment by roughpandaz** [comment]
@martinheidegger - Just waiting for the videos to upload it seems.

**Comment by roughpandaz** [comment]
@martinheidegger, @lvivier I've uploaded all the videos onto this channel. please take a look.

https://www.youtube.com/channel/UCSw3b6AjHvCwRVpT2LW2l5w

I've also got photos if you need them

**Comment by iancrowther** [comment]
@teomurgi it will do until the 1st commit :-)

**Comment by beltran-rubo** [comment]
Two videos from NodeSchool Seville (Spain)

https://youtu.be/1E3kcsvsq3s
https://youtu.be/54JH44y_mns

**Comment by martinheidegger** [comment]
Here is Osaka (transcript in the description)

https://www.youtube.com/playlist?list=PL77xOyqOy19RCg7TIrdtEqudOOEUrcE4o

**Comment by martinheidegger** [comment]
And some stills here: https://github.com/nodeschool/osaka/tree/gh-pages/photos/id-2015

**Comment by jonotron** [comment]
Here is Kamloops:

https://copy.com/3bzQV72vaGw4RmyO

**Comment by ishtiaque23** [comment]
Hello World! Here is Dhaka!

https://www.youtube.com/watch?v=0YneGGzY0HA

**Comment by iancrowther** [comment]
Am requesting all mini-films be uploaded and links provided by Friday 12th June.

**Comment by grabbou** [comment]
Sounds like the deadline for our editing process as well :D But +1, was going to write the same.

**Comment by iancrowther** [comment]
@grabbou let me know if you need anything

**Comment by martinheidegger** [comment]
@RongxinZhang I am still not able to access the channel/videos (private?)

**Comment by keokilee** [comment]
Here's @nodeschool/honolulu's closing video.

https://goo.gl/photos/hVqpjAh4Qumz7HMw8

**Comment by jeduan** [comment]
Please let me know if you'd prefer this on Youtube or Vimeo is good
https://vimeo.com/130505469

**Comment by marulango** [comment]
for the Mexico City video, let me know if subtitles would be needed or if you'd like me to share the footage.

**Comment by iancrowther** [comment]
Would anyone like to take a stab at this?  It would be awesome for this years PR

**Comment by iancrowther** [comment]
Hi, 

Firstly, apologies for hitting up everyone!

Secondly, I have asked a video editor here in the UK to edit last years videos and photos into a mini-film.  We now need to gather as much raw footage as possibe!!!

A lot of the links posted in this issue dont work due to permissions or the fact they are hosted. I know its a pain in the rear, but can you help me gather up last years footage?

@mcollina @gangstead @afronski @no9 @hrayatnia @sequoia @martinheidegger @jasonrhodes @makenai @bajtos @julianduque @forres @jeduan @asbjornenge @blakmatrix @keokilee @davyengone @jonotron @a0viedo @yoshuawuyts @grabbou @ralucas @usmantahirr @marinintim @sericaia @timoxley @finnp @tdd @pricco @gaboesquivel @lvivier @llkats @awaterma @colinloretz @paulohp @spikeheap @alexfernandez @jeffjewiss @yosuke-furukawa @beltran-rubo @majgis @kwakayama @chitopolo @diegowifi @cronopio @ryanramage @gmauricio @az7arul @iamchathu @kytwb @pedroromn @cfsghost @shime 

I'm going to put a "loose" deadline of the 18th Dec so we can get started.  Please dig deep!

**Comment by alexfernandez** [comment]
Our videos from International School Madrid:
- Me gusta NodeSchool: https://www.youtube.com/watch?v=mQUtAnBirJc
- Hello from Madrid: https://www.youtube.com/watch?v=r_cr3UePv9M
- International Day: https://www.youtube.com/watch?v=UQqGQvy4uT4

Looking forward to see the result!

**Comment by iancrowther** [comment]
@alexfernandez can I access the raw files?

**Comment by alexfernandez** [comment]
I will ask the video editors about it.

**Comment by iancrowther** [comment]
ah great - thats what my guy here has asked for

**Comment by jonotron** [comment]
@iancrowther I was wondering what might have happened to this project. Excited to see it is still breathing. Just checked the link for the Kamloops, BC event: (https://copy.com/3bzQV72vaGw4RmyO) It still works

**Comment by iancrowther** [comment]
Im super keen to capture the day, its going to be a big ask to get raw content though!!

the video guy has made some amazing work, so lets hope we can get enough for him to work with..

**Comment by iancrowther** [comment]
any takers?

**Comment by marulango** [comment]
@iancrowther let me find the raw files and I'll share them :D

**Comment by iancrowther** [comment]
yay

**Comment by iancrowther** [comment]
thanks @marulango - received

fyi - you can share files to ian@nexttick.io

**Comment by iancrowther** [comment]
Please can you help me gather assets from the day, photos, video, chapter logos..

https://drive.google.com/folderview?id=0B1E3fBFiidMXS2txV0N2ejVKNjg&usp=sharing

**Comment by iancrowther** [comment]
ok this is now done!
