### ISSUE TITLE
Hello From Taipei

### ISSUE THREAD

**Issue by dca** [nodeschool/international-day#88]
Hello everybody, 

we launched from 5/23 02:00 (GMT+0) to 5/23 10:00 (GMT+0). More than 150 people start to learn node.js here.

[2015 nodeschool International Day @Taipei](https://github.com/nodeschool/taiwan/issues/10)

![11214307_360595060797195_7972985513448226330_n](https://cloud.githubusercontent.com/assets/226619/7784885/21e2eaa6-01aa-11e5-8086-7a5697ced00a.jpg)

![11181828_360595064130528_459411646922603222_n](https://cloud.githubusercontent.com/assets/226619/7784888/30b6b4b8-01aa-11e5-9539-001fc13c800e.jpg)

![11265296_360595067463861_9168179578403716674_n](https://cloud.githubusercontent.com/assets/226619/7784890/38270e82-01aa-11e5-8822-6343f013f49a.jpg)

![11216254_360595077463860_3169919159569166807_n](https://cloud.githubusercontent.com/assets/226619/7784891/3cb27630-01aa-11e5-9918-6776f5f8ad93.jpg)

![11209500_360595057463862_6283365443247325795_n](https://cloud.githubusercontent.com/assets/226619/7784892/3f3d9d1c-01aa-11e5-97f3-f1c177ef4838.jpg)

cc @cfsghost

**Comment by SimonSun1988** [comment]
Cooooooool

**Comment by andrewchen30** [comment]
I think our people is more than other country XD

**Comment by iancrowther** [comment]
your event is fantastic

**Comment by iancrowther** [comment]
have you stopped by  http://appear.in/nodeschool?
