### ISSUE TITLE
international day mini-film

### ISSUE THREAD

**Issue by max-mapper** [nodeschool/international-day#9]
I think it would so cool if we could get organizers to record video + audio at their events so that we can edit it into a mini-film afterwards.

For example, we could request that each event interviews a couple attendees and ask them the same set of questions. Or do something more fun like have every group do some wacky dance moves that @nvcexploder choreographs.

Does anyone have experience doing this kind of thing or have funny ideas?

**Comment by nvcexploder** [comment]
This sounds rad - although I'm not much of a choreographer. If we generate
enough video content, folks interested in editing can tell any story they
like about the event. :)

**Comment by iancrowther** [comment]
i think this is actually a fantastic idea, do we know anyone who could edit down the video afterwards?  maybe an existing video sponsor?

**Comment by nvcexploder** [comment]
I don't know, but I know there's a lot of folks here that may be interested
- I will start asking around! :D

**Comment by iancrowther** [comment]
would be great, I've really struggled to find gratis video work in London and believe me I have tried for lnug.org

**Comment by grabbou** [comment]
Part of our company based in London is doing some video adverts and media stuff, mainly for apps and products that are about to launch, but we can merge all of the interviews into one video if that's the case. I have the most recent video we've made last week somewhere, I'll try to find and share it with you.

Speaking scenario-wise, although having english-spoken video would've been quite cool, I actually think that we can use the idea, that Node.js is everywhere and JS connects people by just asking people to say something really short in their native language... kind of "one sentence" or something?

CC: @tomfrew

**Comment by iancrowther** [comment]
@grabbou fantastic.  

Can you take a look at [Issue 5](https://github.com/nodeschool/international-day/issues/5#issuecomment-78358051)

Im based in London too so you want to grab a coffee and bounce some ideas?

**Comment by tdd** [comment]
Hey there,

NodeSchool Paris happens at Mozilla Paris (Mozilla's EU Headquarters, basically); their video capacity does not extend to "handheld video work", but we could def use a simple iPhone 5S (or above) to capture video questions and general pans of the room at work.

So yes, if we could at least come up with a common scenario for such a video (intro, questions, how many interviewees, what to show of the general room / audience), this would make it easier to montage later on :smile: 

Here's my initial draft proposal (no particular shooting order, editing will make that homogenous):
1. 1+ organizer(s) facing cam, loud "welcome to NodeSchool <Chapter>!" in the local language
2. General pan of the room at work
3. (If relevant) General pan of the venue
4. (If applicable/relevant) General pan of lunchtime
5. 2+ interviews of attendees with the same questions:
   - What's your name?
   - Had you done JS / Node before?
   - What do you like best about NodeSchool?

Let's refine this so we can shoot that on our next event (Paris' 2nd NodeSchool Day is on April 11).

**Comment by iancrowther** [comment]
@nodeschool/international-day 

@martinheidegger and I were discussing what screen recorder to use to help with the mini film.  make.tv looks like it would do the trick.  @grabbou do you have any specific requirements/thoughts/feedback? 

If were happy with the choice, Can we schedule an test call on Friday May 8th at 12:00 GMT?

**Comment by Sequoia** [comment]
Is anyone bottom-lining the video collection/editing/publishing?

**Comment by iancrowther** [comment]
hey @Sequoia 

just to be clear, is "bottom-lining" the same as ownership?

**Comment by Sequoia** [comment]
@iancrowther no I mean "is anyone actually _doing_ this?" We can all collect footage but someone needs to actually go over it all, edit, tie it all together, yes?

**Comment by grabbou** [comment]
Hey guys,

@iancrowther I am happy to have a test call anytime starting from tomorrow, just ping me either here on gitter / email in case I am not responding. 

@Sequoia, @iancrowther, in terms of merging all the things into a movie with a proper editing I am happy to take it. Here's a sample `advert` we've done recently in case you are curious how we do it on daily basis (https://www.youtube.com/watch?v=JRBOx934R-A). Ignore the content, just focus on the transitions and stuff. If that's somehow good enough for our purposes, let me know :)

**Comment by Sequoia** [comment]
👏👏 @grabbou go for it! 👍

**Comment by grabbou** [comment]
Cool, do we have any specific scenario for the mini-movie already?

**Comment by iancrowther** [comment]
@grabbou if you can define a simple script, that would be amaze.

Were just going to ask each chapter to use youtube live to record an intro and exit video.  You can download the video and commit it so you have a collection of content.

"Hi, were xxx and we love nodeschool" kinda thing.  We can use the chapter stickers and splashes etc.

I really need your input into what content you need so I can communicate it.

**Comment by iancrowther** [comment]
@grabbou re test call, we did it :-) Youtube live was the outcome

@alanshaw is updating the docs

**Comment by grabbou** [comment]
Yeah. Opening a new issue just to keep it clear. Feel free to close this one.

**Comment by grabbou** [comment]
Yeah, I've spoken to @tomfrew who's the creative brain behind the team I am a part of and he's been actually planning all that stuff from the very beginning. We should have a basic script / tips by tomorrow we can then resend to other chapters but we have few other questions as far as I am aware.

Also - we should contact chapters and get the list of who is going to record a video so we can polish the script and make sure the video is not too long.

**Comment by tomfrew** [comment]
Hi Guys,

We've put together a quick plan with the aim of keeping things quite simple. The aim is to get film as much as possible and then we can edit it all together. 

With this in mind we have some specific shots that we think would work best. So if everyone could try and capture the following:
-  Establishing shot of the venue from outside of the building
-  A few shots inside of people mingling and talking
-  Some shots walking around the room using the Hyperlapse app if possible
-  Group shot of everyone shouting "Hello from xxx" in english.
-  Group shot of everyone shouting "We love Nodeschool" in their native language
-  Panning shots of the room with everyone on laptops

Other shots that would be great:
-  Talking heads style shots of the attendees as they arrive saying what they are hoping to get out of the event.
-  Talking heads style shots of the attendees at the end saying what they thought of the event.
-  Shots over people leaving at the end

With the footage, we can create an online folder / FTP that everyone can upload into.
Keen to hear any feedback that you might have?

**Comment by martinheidegger** [comment]
Awesome. I plan to take a few short videos of the location today/tomorrow in preparation of the event!

**Comment by iancrowther** [comment]
can we integrate this into participating.md and then close. ty
