### ISSUE TITLE
Why did I close all the "Hello from ..." issues?

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/international-day#95]
First of all: Thanks for participating. It was a blast for me and I hope for you too. I took the liberty to close the "Hello from" issues and add a `rollcall-2015` label to it. This way we have sort of "clean" data to process. But that is all there is to it! Cheers and thx again for shouting out!

**Comment by iancrowther** [comment]
+1

**Comment by martinheidegger** [comment]
Please keep open for a day or two in case other people wonder as well
