### ISSUE TITLE
Post-Mortem worklist

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/international-day#96]
Some things need to be cleaned up
- [x] International Day Banner should be removed from NodeSchool Homepage
- [x] Add link to international page / series lower in the page hierarchy, we want the video there somewhere - **in-progress**
- [x] International Day Page should tell a big thank-you and tell people that it was awesome and a hint that we will try to do that again in future!
- [x] Attempt to get more statistics from the chapters and add them [here](https://docs.google.com/a/we-are-root.com/forms/d/1Pg8QS09IggOsH8etXK7zDUqglobHBFD0OJvP5za2MwU/viewform)
- [x] Collect the video information
- [x] ~~Prepare a text for the newsletter!~~
- [x] Write a list with things good to remember for when we hold the next event (checklist of sorts)
- [x] Get org's stories combined into a blog or something
- [x] Scrape enrollement info 
- [x] add alumni page to website - **in-progress**
- [x] Update org chart and get people onboarded - **in-progress**

**Comment by Sequoia** [comment]
2nd to last instruction on this checklist is to write a checklist. Is this... :scream_cat: a recursive checklist?!? :smile_cat:

**Comment by martinheidegger** [comment]
The recursion ends when people stop being interested in nodeschool days, but else: you are right ;)

**Comment by iancrowther** [comment]
its a retro.. maybe send out a feedback form?

**Comment by martinheidegger** [comment]
@iancrowther you are the boss :wink:

**Comment by iancrowther** [comment]
"Collect the video information" - wow! that was a bit of a task.. must put in a better collection mechanism next year! maybe gather on the day!

**Comment by iancrowther** [comment]
"Get org's stories combined into a blog or something"

Tokyo: http://amagitakayosi.hatenablog.com/entry/2015/05/28/121346
Taiwan: http://fred-zone.blogspot.tw/2015/05/nodeschool-international-day.html
Lisbon: http://blog.yld.io/2015/06/01/nodeschool-international-day/
Costa Rica: http://costaricajs.co/2015/05/Resumen-NodeSchool-International-Day-Mayo-2015-San-Jose-Costa-Rica/

**Comment by iancrowther** [comment]
"Attempt to get more statistics from the chapters and add them" - we have gathered enough for the video editor to use.

I have the stats in a gdoc if they are req'd

**Comment by iancrowther** [comment]
"International Day Page should tell a big thank-you and tell people that it was awesome and a hint that we will try to do that again in future!" - a bit late now, lets just update the main site

**Comment by iancrowther** [comment]
"Prepare a text for the newsletter!" - created independant issue

**Comment by iancrowther** [comment]
"Scrape enrollement info and add alumni page to website" - individual issues

**Comment by iancrowther** [comment]
"Write a list with things good to remember for when we hold the next event (checklist of sorts)" - https://github.com/nodeschool/international-day/issues/108

**Comment by iancrowther** [comment]
"Add link to international page / series lower in the page hierarchy, we want the video there somewhere" - dupe

**Comment by iancrowther** [comment]
"Write a list with things good to remember for when we hold the next event (checklist of sorts)" - dupe
