### ISSUE TITLE
Saturday 21st May 2016 - oooooooooh it's that time again!! 

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#97]
Can we start putting some proposed dated in for the 2016 international-day

**Saturday 21st May 2016**

**Comment by iancrowther** [comment]
@nodeschool/chapter-organizers 

We need timezone champions for:
- North America
- South America
- Asia
- Oceania

@a0viedo @rosskukulinski @martinheidegger @timoxley ?

**Comment by eafelix** [comment]
great! i cant wait :+1: :smile:

**Comment by timmarinin** [comment]
:+1:

**Comment by martinheidegger** [comment]
I am here.

**Comment by martinheidegger** [comment]
This time we do sign-up through google docs!

**Comment by julianduque** [comment]
Awesome!!

**Comment by cronopio** [comment]
21st May 2016 sounds good!

**Comment by iancrowther** [comment]
@martinheidegger we need a new registration.md then

Can we start to jot down a master plan.

**Comment by takempf** [comment]
Oakland reporting.

**Comment by rosskukulinski** [comment]
By then I'll be working with @nodeschool/philadelphia and can cover US ET.

**Comment by andrenventer** [comment]
Hermanus :+1:

**Comment by iancrowther** [comment]
I have started a 2016 branch but can't push it! am a bit blocked atm :-( help me o-b-wan!

**Comment by fmoliveira** [comment]
Awesome!

Campinas reporting, we'll cover timezone BRT -03:00 (South America / Sao Paulo).

**Comment by iancrowther** [comment]
awesome

**Comment by riyadhalnur** [comment]
Dhaka reporting at GMT +6

@az7arul @zhdzmn @ishtiaque23

**Comment by iancrowther** [comment]
I have now pushed the 2016 branch, as a result 2015 has been given "protected" status in github.

**Comment by iancrowther** [comment]
I have updated the [Org Chart](https://github.com/nodeschool/international-day/blob/2016/ORGANISERS.md) and removed last years timezone champions ready for 2016.  

Ideally we have a couple of champions for each timezone to share the load, and even better would be if last years champions would volounteer themselves again to share your experience.  I am expecting a lot more chapters this year!

If you would like to take ownership of a timezone (you rock!), then please add yourself to the org chart via a pull request so we can discuss.  We are still outlining this years responsibilities and now know its a long but rewarding day.

**Comment by rvagg** [comment]
@damonoehlman @joshgillies @sidorares need an AU timezone champion on this, do any of you have the bandwidth to track it?

**Comment by rvagg** [comment]
also @SomeoneWeird ^

**Comment by sidorares** [comment]
I think @SomeoneWeird was much more involved in nodescool lately then any other but if he is busy I can do ( AEST, UTC+10 )

**Comment by ghost** [comment]
@sidorares @SomeoneWeird @joshgillies @rvagg ~ happy to provide venue and food/drink for the melbourne chapter.

**Comment by jesstelford** [comment]
I could help on the day with the Sydney chapter (but wont have capacity to organise)

**Comment by NorthDecoder** [comment]
It looks like [Tacoma WA](https://github.com/nodeschool/tacoma) is in UTC-8. What is required of the organizers?  That is a pretty big area to cover.  Maybe someone from each chapter in the timezone would like to assist?

**Comment by tdd** [comment]
May 21 sounds fine for FR, too. I can have NodeSchool Paris happen on that date. Smack between the Whit weekend and our Mother's day weekend, basically the ONLY May weekend not already spoken for. Well done! :grin:

**Comment by iancrowther** [comment]
thanks @tdd

**Comment by iancrowther** [comment]
@NorthDecoder in short timezone champions are online for the duration of their time slot.  You need to be available to help chapters engage with the day.  This usually involves sharing links, making sure chapter organisers know when to come online, highlight how to join the video link, remind them to record an intro video.  There will be a checklist.  Its good to have a couple of organisers per timezone as there are spikes when it seems everyone is online at once!

Above all else though, you need to encourage chapter a to have a chat with chapter b.  Its fun to talk to a chapter in another country and get to know people.  

Does that clarify or raise more questions?

**Comment by fforres** [comment]
Sounds great for CL! 
It's a national holiday though,  but that can work better for the event :smiley:

**Comment by a0viedo** [comment]
Great proactivity @iancrowther! I would happily champion South America but would also want to open the opportunity to other folks as well. Maybe @julianduque or @fforres are interested?

**Comment by iancrowther** [comment]
@a0viedo yeah It would be great for you to work with someone new to share you knowledge etc

**Comment by julianduque** [comment]
I would love to champion South America but for that time I'll be in Florida, so if anyone is going to organize something in Florida I'll be there to help

**Comment by iancrowther** [comment]
Florida would be cool - can't remember them from last year? Beachschool :-)

**Comment by fforres** [comment]
I'd love to! :heart: 
Not only me, but the CL team is really excited as well 
(We can always use some tips though @a0viedo & @julianduque)

**Comment by iancrowther** [comment]
so its 2016, Happy New Year! 

Can you help me with some website updates? also as organisers can you help me populate the organsiers.md as per https://github.com/nodeschool/international-day/issues/98#issuecomment-168308908. if we all chip in a little, well have this ready in no time :-)

@marinintim @julianduque @martinheidegger @cronopio @Fauntleroy @rosskukulinski @andrenventer  @fmoliveira @riyadhalnur @fforres @a0viedo @tdd @olizilla @NorthDecoder @jesstelford @louiscntr @sidorares

**Comment by thebergamo** [comment]
Happy new year fellows!!

São Paulo reporting here!!

**Comment by iancrowther** [comment]
hey @thebergamo happy new year to you too :-)

I have updated the website for 2016 - http://nodeschool.io/international-day/

Please review and raise any issues you come across

**Comment by thebergamo** [comment]
Cool.. I need see better how the international day works.. I'm very outdated about nodeschool chapters :(

**Comment by iancrowther** [comment]
@thebergamo some help with the website would be awsm!

**Comment by thebergamo** [comment]
where the issues to help? =D

**Comment by iancrowther** [comment]
checkout https://github.com/nodeschool/international-day/issues, most are website related at the minute

**Comment by thebergamo** [comment]
Ok, will see

**Comment by iancrowther** [comment]
this just about sums up last years calculations!!

https://www.youtube.com/watch?v=uW6QqcmCfm8

;-)

**Comment by gautamarora** [comment]
Hi everyone. This is NYC reporting!
Looks like we already have a TZ champion for US ET.

**Comment by iancrowther** [comment]
@gautamarora - additional hands always welcome
