### ISSUE TITLE
Sponsorship guidelines

### ISSUE THREAD

**Issue by Sequoia** [nodeschool/international-day#99]
# possibility a

Sponsorship **requirements**
# possibility b

Sponsorship requirements **to be an officially listed nodeschool event**
# possibility c

Sponsorship **guidelines**

**Comment by Sequoia** [comment]
:+1: option c (guidelines):

Explain the ✨Spirit of Nodeschool✨ and write recommendations for sponsorship for people to stay in keeping with "nodeschool culture"/accessibility/sharing/etc..

I can take a swing at writing such a thing if ppl like that idea.

## my issues with the other choices

"A" rules: unless someone's gonna make a nodeschool international day org, trademark the name, set up governance model etc. and actually enforce the rules. Otherwise the rules are both arbitrary (who sets the rules? how? I certainly don't want to be in charge of answering these questions...) and unenforceable.

"B": basically, it's a hassle. The Lords of Nodeschool could write sponsorship requirements to be included in official event listings. That way it's still opt-in & ppl can make their own choice about how important it is to them to be in main event listing. Even that seems like a hassle tho, and equally arbitrary without some sort of formal/democratic process.

**Comment by max-mapper** [comment]
:+1: option c (guidelines), love the "Spirit of Nodeschool" idea

**Comment by Sequoia** [comment]
OT: If I were a drawer I'd draw a li'l ship :boat: with maybe ribbon over it like a tattoo: "Spirit of Nodeschool." Nodeschool Int'l Day II: The Spirit of Nodeschool :stuck_out_tongue: memorial hex sticker.

**Comment by iancrowther** [comment]
:-)

is this for Nodeschool in general or for international day?  Im not sure what we would use the sponsorship for?

**Comment by Sequoia** [comment]
@iancrowther I created this ticket to move extended discussion off #98, which was for international day _events_. I've used sponsorship in the past to pay for coffee, lunch, stickers, shirts, & to bring in additional trainers. Paying an honorarium to organizers/trainers really helps alleviate burnout and encourages participation, especially among people who can't afford to work completely for free. I highly recommend it if you can get the $! It allowed us to have a very nice event at no expense to participants (i.e. tickets were free).

**Comment by iancrowther** [comment]
@Sequoia i like the idea of an "honorarium", maybe via gittip of something.. food for thought.

I still think this guideline is for nodeschool chapters.  international-day is not really a chapter, its just an event that brings chapters together.

**Comment by Sequoia** [comment]
@iancrowther I created this ticket for discussion of "sponsorship rules" for NSID, which topic was raised by @martinheidegger in #98. Perhaps the two of you can hash out whether this is a chapter or event thing & report back; alternately we can just strike "sponsorship rules" from the prep list & call it done! As the Germans say, "es ist mir egal" :smile: I'm happy with no rules, but if rules there must be I wanted to throw in my $.02 as this affects me & my planning.

**Comment by mikeal** [comment]
what exactly is a "sponsored nodeschool?" just a nodeschool that has a sponsor or one run by a company who is putting up their space/money or what?

**Comment by iancrowther** [comment]
@mikeal how are they different?

to me its simply a chapter's event sponsorship, either office space or cash

**Comment by mikeal** [comment]
@iancrowther so, if NodeSchool's need money I can solve that problem with money :) but, if what they need is well located temporary office space that isn't something as easily solvable with money :)

**Comment by Sequoia** [comment]
"Nodeschool is a loose confederation of like-minded JavaScripters who enjoy teaching and sharing skills. It is not a formal organization, it has no governing committee or by-laws.  As such, there is no one with the responsibility (or authority) to make "rules" or decide what is or is not a "Nodeschool" event. The name "Nodeschool" is un-trademarked, available for any to use in the service of spreading the good news about JavaScript!

While there are no "rules," shared values are a large part of what makes a group of people a community, and the Nodeschool community has a few of those!

_some ideas:_
1. Inclusivity
2. Accessibility

In the interest of inclusivity and accessibl :construction: _not finished_ :construction: ...low or no fee for attendees... ...chiefly non-corporate... ...non-profity?... ...sponsorship is up to each event organizer, but if it's relied upon it should provide value to attendees and defray the

:point_up: I'm just trying to write something up cuz there seems to be a lot of confusion around this and at the end of the day **there are no sponsorship rules** because  **there's no one with the authority to make or enforce these rules**.

**Comment by iancrowther** [comment]
@sequoia Guidelines are helpful and appreciated. They are there for chapter orgs as it continues with the decentralised theme.

@mikeal understood, is great to have the support. we could do with a kitty for the international day video editor! Other than that, org level kitty just complicates things I think.

**Comment by Sequoia** [comment]
I sort of went off track with the "principals"/guidelines I was suggesting for sponsorship when I tried to actually articulate recommendations. What are they? Don't charge attendees? This doesn't work if you need to rent space/buy coffee/can't get sponsorship. Don't solicit or take any sponsorship? This pushes costs onto volunteers/organizers or forces them to charge attendees. Don't spend money? Well, I am personally not going to endorse or follow this rec. as I like to put on events with food, coffee etc..

My opinion: **We're seeking a solution where there's no problem**. What is the issue that is forcing us to write rules/recommendations about sponsorship? Was there some controversy or incident? If not, **let's leave well enough alone** and let each organizer decide what's best for their event. :smile:

Closing this ticket as `WONTFIX`. @martinheidegger if you (or anyone) wants to propose _specific_ guidelines around sponsorship, please reopen, otherwise this LGTM!
